//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Negar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap install {
            get {
                object obj = ResourceManager.GetObject("install", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توافق‌نامه‌ی استفاده از نرم‌افزار
        ///اینجانب خریدار یک نسخه از نرم‌افزار سپهر یا دریافت‌کننده نسخه نمایشی آن، با نصب این نرم‌افزار تمامی شرایط ذیل را  قبل از خرید، در نسخه نمایشی یا از طریق سایت مطالعه کرده و اینک با دریافت و درک مفاد آن به عنوان شرط استفاده از نرم‌افزار، بدون هیچ قید و شرطی کلیه شرایط ذیل را با فشاردادن کلید (من توافقنامه را خواندم) جهت نصب نرم‌افزار به عنوان تایید الکترونیکی خود قبول می‌نمایم:
        ///1. مالکیت معنوی این نرم‌افزار متعلق به صاحب امتیاز آن (شرکت رایان پرتونگار) است. این نرم‌افزار تح [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseAgreement {
            get {
                return ResourceManager.GetString("LicenseAgreement", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Setup {
            get {
                object obj = ResourceManager.GetObject("Setup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
