C:\Projects\Negar\5.Tools\GacInstaller\GacInstaller.exe i "C:\Projects\Negar\4.Components\#Third.Party.Components\ChilkatDotNet2.Dll"
C:\Projects\Negar\5.Tools\GacInstaller\GacInstaller.exe i "C:\Projects\Negar\4.Components\#Third.Party.Components\ComponentFactory.Krypton.Toolkit.Dll"
C:\Projects\Negar\5.Tools\GacInstaller\GacInstaller.exe i "C:\Projects\Negar\4.Components\#Third.Party.Components\DevComponents.DotNetBar2.Dll"
C:\Projects\Negar\5.Tools\GacInstaller\GacInstaller.exe i "C:\Projects\Negar\4.Components\#Third.Party.Components\mCoreLib.Dll"