//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sepehr.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sepehr.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap Accept {
            get {
                object obj = ResourceManager.GetObject("Accept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap AccountSetting {
            get {
                object obj = ResourceManager.GetObject("AccountSetting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ACLDiagram {
            get {
                object obj = ResourceManager.GetObject("ACLDiagram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ACLManage {
            get {
                object obj = ResourceManager.GetObject("ACLManage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap AddinFields {
            get {
                object obj = ResourceManager.GetObject("AddinFields", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap AddMed {
            get {
                object obj = ResourceManager.GetObject("AddMed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Address {
            get {
                object obj = ResourceManager.GetObject("Address", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap AddSmall {
            get {
                object obj = ResourceManager.GetObject("AddSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Allow {
            get {
                object obj = ResourceManager.GetObject("Allow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap AllowedUsers {
            get {
                object obj = ResourceManager.GetObject("AllowedUsers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Apply {
            get {
                object obj = ResourceManager.GetObject("Apply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Ascending {
            get {
                object obj = ResourceManager.GetObject("Ascending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Automatic {
            get {
                object obj = ResourceManager.GetObject("Automatic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Backup {
            get {
                object obj = ResourceManager.GetObject("Backup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Bank {
            get {
                object obj = ResourceManager.GetObject("Bank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BillsTemplate {
            get {
                object obj = ResourceManager.GetObject("BillsTemplate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Blank {
            get {
                object obj = ResourceManager.GetObject("Blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Browse {
            get {
                object obj = ResourceManager.GetObject("Browse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Cash {
            get {
                object obj = ResourceManager.GetObject("Cash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CashManage {
            get {
                object obj = ResourceManager.GetObject("CashManage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CashMonitor {
            get {
                object obj = ResourceManager.GetObject("CashMonitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CashReport {
            get {
                object obj = ResourceManager.GetObject("CashReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CDBurnerStart {
            get {
                object obj = ResourceManager.GetObject("CDBurnerStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ChangeUser {
            get {
                object obj = ResourceManager.GetObject("ChangeUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Collapse {
            get {
                object obj = ResourceManager.GetObject("Collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Config {
            get {
                object obj = ResourceManager.GetObject("Config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ContactUs {
            get {
                object obj = ResourceManager.GetObject("ContactUs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Cost {
            get {
                object obj = ResourceManager.GetObject("Cost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Costs {
            get {
                object obj = ResourceManager.GetObject("Costs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Cut {
            get {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Data {
            get {
                object obj = ResourceManager.GetObject("Data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DeleteMed {
            get {
                object obj = ResourceManager.GetObject("DeleteMed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DeleteSmall {
            get {
                object obj = ResourceManager.GetObject("DeleteSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Deny {
            get {
                object obj = ResourceManager.GetObject("Deny", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Descending {
            get {
                object obj = ResourceManager.GetObject("Descending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DesignableReports {
            get {
                object obj = ResourceManager.GetObject("DesignableReports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Dicom {
            get {
                object obj = ResourceManager.GetObject("Dicom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Discount {
            get {
                object obj = ResourceManager.GetObject("Discount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Discounts {
            get {
                object obj = ResourceManager.GetObject("Discounts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DocTemplates {
            get {
                object obj = ResourceManager.GetObject("DocTemplates", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DocToolbar {
            get {
                object obj = ResourceManager.GetObject("DocToolbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DocumentAdd {
            get {
                object obj = ResourceManager.GetObject("DocumentAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DocumentCheck {
            get {
                object obj = ResourceManager.GetObject("DocumentCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DocumentDelete {
            get {
                object obj = ResourceManager.GetObject("DocumentDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DocumentEdit {
            get {
                object obj = ResourceManager.GetObject("DocumentEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DocumentSetting {
            get {
                object obj = ResourceManager.GetObject("DocumentSetting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DownLarge {
            get {
                object obj = ResourceManager.GetObject("DownLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EditLarge {
            get {
                object obj = ResourceManager.GetObject("EditLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EditSmall {
            get {
                object obj = ResourceManager.GetObject("EditSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EventsLogs {
            get {
                object obj = ResourceManager.GetObject("EventsLogs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Expand {
            get {
                object obj = ResourceManager.GetObject("Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ExportToExcel {
            get {
                object obj = ResourceManager.GetObject("ExportToExcel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Find {
            get {
                object obj = ResourceManager.GetObject("Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap FreeLockedRow {
            get {
                object obj = ResourceManager.GetObject("FreeLockedRow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GroupsManage {
            get {
                object obj = ResourceManager.GetObject("GroupsManage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HelpMed {
            get {
                object obj = ResourceManager.GetObject("HelpMed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HowTo {
            get {
                object obj = ResourceManager.GetObject("HowTo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [ImagingSystem];
        ///-- ============================
        ///-- لیست بانك ها
        ///--DELETE FROM [ImagingSystem].[Accounting].[Banks] WHERE [ID] &gt; 13;
        ///--DBCC CHECKIDENT (&apos;ImagingSystem.Accounting.Banks&apos;, RESEED, 13);
        ///-- ============================
        ///-- ارتباط صندوق ها و صندوقداران
        ///DELETE FROM [ImagingSystem].[Accounting].[CashiersCashes];
        ///-- ============================
        ///-- لیست صندوق ها
        ///DELETE FROM [ImagingSystem].[Accounting].[Cashes];
        ///DBCC CHECKIDENT (&apos;ImagingSystem.Accounting.Cashes&apos;, RESEED, 0);
        ///-- ======= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IMSClearCommand {
            get {
                return ResourceManager.GetString("IMSClearCommand", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap InfoLarge {
            get {
                object obj = ResourceManager.GetObject("InfoLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap InfoSmall {
            get {
                object obj = ResourceManager.GetObject("InfoSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap InsLogo {
            get {
                object obj = ResourceManager.GetObject("InsLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Job {
            get {
                object obj = ResourceManager.GetObject("Job", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Language {
            get {
                object obj = ResourceManager.GetObject("Language", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Left {
            get {
                object obj = ResourceManager.GetObject("Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap LeftLarge {
            get {
                object obj = ResourceManager.GetObject("LeftLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap LeftMed2 {
            get {
                object obj = ResourceManager.GetObject("LeftMed2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Licenses {
            get {
                object obj = ResourceManager.GetObject("Licenses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Minus {
            get {
                object obj = ResourceManager.GetObject("Minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Money {
            get {
                object obj = ResourceManager.GetObject("Money", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MoneyLogo {
            get {
                object obj = ResourceManager.GetObject("MoneyLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Movie {
            get {
                object obj = ResourceManager.GetObject("Movie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NewPat {
            get {
                object obj = ResourceManager.GetObject("NewPat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NewRef {
            get {
                object obj = ResourceManager.GetObject("NewRef", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Password {
            get {
                object obj = ResourceManager.GetObject("Password", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PatEdit {
            get {
                object obj = ResourceManager.GetObject("PatEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PatientFile {
            get {
                object obj = ResourceManager.GetObject("PatientFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PatientID {
            get {
                object obj = ResourceManager.GetObject("PatientID", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PatientNameAddLogo {
            get {
                object obj = ResourceManager.GetObject("PatientNameAddLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PatLastRef {
            get {
                object obj = ResourceManager.GetObject("PatLastRef", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PatLocations {
            get {
                object obj = ResourceManager.GetObject("PatLocations", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PatRef {
            get {
                object obj = ResourceManager.GetObject("PatRef", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Payment {
            get {
                object obj = ResourceManager.GetObject("Payment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PayMoney {
            get {
                object obj = ResourceManager.GetObject("PayMoney", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Performers {
            get {
                object obj = ResourceManager.GetObject("Performers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Physician {
            get {
                object obj = ResourceManager.GetObject("Physician", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PhysicianLogo {
            get {
                object obj = ResourceManager.GetObject("PhysicianLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Plus {
            get {
                object obj = ResourceManager.GetObject("Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [PatientsSystem].[Patients].[List];
        ///DBCC CHECKIDENT (&apos;PatientsSystem.Patients.List&apos;, RESEED, 0);
        ///-- =======================================
        ///DELETE FROM [PatientsSystem].[Patients].[Jobs];
        ///DBCC CHECKIDENT (&apos;PatientsSystem.Patients.Jobs&apos;, RESEED, 0);
        ///-- =======================================
        ///TRUNCATE TABLE [PatientsSystem].[Patients].[IDPool];
        ///-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@
        ///-- بیمه های سازمان های اصلی باقی می مانند
        ///DELETE FROM [PatientsSystem].[Clinic].[Insurances] WHERE [ID] &gt; 6;
        ///DBC [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PMSClearCommand {
            get {
                return ResourceManager.GetString("PMSClearCommand", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap PrintBill {
            get {
                object obj = ResourceManager.GetObject("PrintBill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PrintGrid {
            get {
                object obj = ResourceManager.GetObject("PrintGrid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PrintPreview {
            get {
                object obj = ResourceManager.GetObject("PrintPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PrintSettings {
            get {
                object obj = ResourceManager.GetObject("PrintSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RebuildDatabase {
            get {
                object obj = ResourceManager.GetObject("RebuildDatabase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RecieveMoney {
            get {
                object obj = ResourceManager.GetObject("RecieveMoney", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RefAccount {
            get {
                object obj = ResourceManager.GetObject("RefAccount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RefDocuments {
            get {
                object obj = ResourceManager.GetObject("RefDocuments", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RefLastDoc {
            get {
                object obj = ResourceManager.GetObject("RefLastDoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ReportAccounting {
            get {
                object obj = ResourceManager.GetObject("ReportAccounting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ReportManage {
            get {
                object obj = ResourceManager.GetObject("ReportManage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ReportManagement {
            get {
                object obj = ResourceManager.GetObject("ReportManagement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ReportMenu {
            get {
                object obj = ResourceManager.GetObject("ReportMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Restore {
            get {
                object obj = ResourceManager.GetObject("Restore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Right {
            get {
                object obj = ResourceManager.GetObject("Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RightLarge {
            get {
                object obj = ResourceManager.GetObject("RightLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RightMed2 {
            get {
                object obj = ResourceManager.GetObject("RightMed2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RPNLogo {
            get {
                object obj = ResourceManager.GetObject("RPNLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RPNLogoSmall {
            get {
                object obj = ResourceManager.GetObject("RPNLogoSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Sch {
            get {
                object obj = ResourceManager.GetObject("Sch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SchAdd {
            get {
                object obj = ResourceManager.GetObject("SchAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SchAdmitPat {
            get {
                object obj = ResourceManager.GetObject("SchAdmitPat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SchAdmitRef {
            get {
                object obj = ResourceManager.GetObject("SchAdmitRef", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SchClearShift {
            get {
                object obj = ResourceManager.GetObject("SchClearShift", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SchEditApp {
            get {
                object obj = ResourceManager.GetObject("SchEditApp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Schedules {
            get {
                object obj = ResourceManager.GetObject("Schedules", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SchHolidays {
            get {
                object obj = ResourceManager.GetObject("SchHolidays", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SchInfo {
            get {
                object obj = ResourceManager.GetObject("SchInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SchSearchApps {
            get {
                object obj = ResourceManager.GetObject("SchSearchApps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SchSearchPatSch {
            get {
                object obj = ResourceManager.GetObject("SchSearchPatSch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SelectAll {
            get {
                object obj = ResourceManager.GetObject("SelectAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SelectNone {
            get {
                object obj = ResourceManager.GetObject("SelectNone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SepehrIcon {
            get {
                object obj = ResourceManager.GetObject("SepehrIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SepehrLogo {
            get {
                object obj = ResourceManager.GetObject("SepehrLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ServicesSettings {
            get {
                object obj = ResourceManager.GetObject("ServicesSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Setting1 {
            get {
                object obj = ResourceManager.GetObject("Setting1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Setting2 {
            get {
                object obj = ResourceManager.GetObject("Setting2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SetUsersInGroups {
            get {
                object obj = ResourceManager.GetObject("SetUsersInGroups", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SMS_Logo_1 {
            get {
                object obj = ResourceManager.GetObject("SMS Logo 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SMS_Logo_2 {
            get {
                object obj = ResourceManager.GetObject("SMS Logo 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SpecianReports {
            get {
                object obj = ResourceManager.GetObject("SpecianReports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Style {
            get {
                object obj = ResourceManager.GetObject("Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SysSecurity1 {
            get {
                object obj = ResourceManager.GetObject("SysSecurity1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap UpLarge {
            get {
                object obj = ResourceManager.GetObject("UpLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap USBOpen {
            get {
                object obj = ResourceManager.GetObject("USBOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap USBRestricted {
            get {
                object obj = ResourceManager.GetObject("USBRestricted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap UsersSettings {
            get {
                object obj = ResourceManager.GetObject("UsersSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Word {
            get {
                object obj = ResourceManager.GetObject("Word", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
