DECLARE @C CURSOR
SET @C = CURSOR FOR 
SELECT [TABLE_CATALOG] , [TABLE_SCHEMA] , [TABLE_NAME] , [COLUMN_NAME] 
FROM [ImagingSystem].INFORMATION_SCHEMA.COLUMNS
WHERE DATA_TYPE = 'nvarchar'
UNION ALL
SELECT [TABLE_CATALOG] , [TABLE_SCHEMA] , [TABLE_NAME] , [COLUMN_NAME] 
FROM [PatientsSystem].INFORMATION_SCHEMA.COLUMNS
WHERE DATA_TYPE = 'nvarchar'
OPEN @C
DECLARE @TABLECATALOG NVARCHAR(128)
DECLARE @TABLESCHEMA NVARCHAR(128)
DECLARE @TABLENAME NVARCHAR(128)
DECLARE @COLUMNNAME NVARCHAR(128)
WHILE @@FETCH_STATUS = 0
	BEGIN
		
		FETCH NEXT FROM @C INTO @TABLECATALOG,@TABLESCHEMA,@TABLENAME,@COLUMNNAME
			BEGIN TRY
				EXEC ('UPDATE '+@TABLECATALOG+'.'+@TABLESCHEMA+'.'+@TABLENAME+
					' SET '+@COLUMNNAME+' = REPLACE('+@COLUMNNAME+' , N''ی'' , N''ی'')')
				EXEC	('UPDATE '+@TABLECATALOG+'.'+@TABLESCHEMA+'.'+@TABLENAME+
					' SET '+@COLUMNNAME+' = REPLACE('+@COLUMNNAME+' , N''ی'' , N''ی'')')
			END TRY
			BEGIN CATCH
			END CATCH
	END
CLOSE @C
DEALLOCATE @C