//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IMSTooltipsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IMSTooltipsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Negar.IMSTooltipsResource", typeof(IMSTooltipsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منوی مدیریت پرونده بیماران.
        ///با استفاده از این منو ، قادر خواهید بود پرونده بیماران را از نوبت دهی ، پذیرش و حساب تا مدارك بیماران مدیریت نمایید..
        /// </summary>
        internal static string btn_MainForm_RTabFile {
            get {
                return ResourceManager.GetString("btn_MainForm_RTabFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منوی دریافت كمك از سیستم.
        ///در این منو قادرید اطلاعاتی كه در مورد كار با نرم افزار نیاز دارید و همچنین آموزش كاربری سیستم را فراخوانی نمایید. همچنین نحوه ارتباط با تولید كننده و همچنین اطلاعات فنی نرم افزار را در این قسمت بدست خواهید آورد..
        /// </summary>
        internal static string btn_MainForm_RTabHelp {
            get {
                return ResourceManager.GetString("btn_MainForm_RTabHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منوی مدیریت بیماران سیستم.
        ///در این منو ، قادرید بیماران ثبت شده در سیستم را جستجو نمایید.
        ///همچنین قادرید بیماران جستجو شده را در بخش های مختلف پذیرش ، حساب ، مدارك و ... مدیریت نمایید..
        /// </summary>
        internal static string btn_MainForm_RTabPatients {
            get {
                return ResourceManager.GetString("btn_MainForm_RTabPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منوی گزارش ها.
        ///با استفاده از این منو قادر خواهید بود گزارش های اصلی سیستم را تولید نمایید.
        ///همچنین مدیریت قالب های قبوض مراجعات بیماران از این قسمت انجام می پذیرد..
        /// </summary>
        internal static string btn_MainForm_RTabReport {
            get {
                return ResourceManager.GetString("btn_MainForm_RTabReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نموی مدیریت تنظیمات سیستم.
        ///با استفاده از این منو ، كلیه تنظیمات پایه ای سیستم ، از قبیل تنظیمات امنیتی ، نوبت دهی بیماران ، مراجعات ، خدمات و بیمه های مراجعات ، حساب مراجعات ، صندوق های تصویربرداری و مدارك مراجعات را قادرید مدیریت نمایید..
        /// </summary>
        internal static string btn_MainForm_RTabSettings {
            get {
                return ResourceManager.GetString("btn_MainForm_RTabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منوی مدیریت سیستم.
        ///با استفاده از این منو قادرید سیستم مدیریت تصویربرداری را مدیریت و بانك اطلاعاتی را بهینه سازی نمایید.
        ///بخش هایی از قبیل مدیریت پشتیبانی و بازیابی ، مدیریت بازسازی ساختار بانك اطلاعات ، نمایش رخدادهای سیستم و... در این منو مدیریت میشوند..
        /// </summary>
        internal static string btn_MainForm_RTabSystemAdmin {
            get {
                return ResourceManager.GetString("btn_MainForm_RTabSystemAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دكمه مدیریت فرم اصلی برنامه.
        ///با كلیك بر روی این دكمه ، لیستی از فرمان های مربوط به فرم اصلی برنامه را مشاهده خواهید نمود..
        /// </summary>
        internal static string btn_MainForm_Start {
            get {
                return ResourceManager.GetString("btn_MainForm_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره تغییرات و بستن فرم.
        ///&lt;div&gt;&lt;/div&gt;پس از فشردن این كلید تنظیمات در بانك اطلاعاتی ذخیره می گردند و فرم بسته می شود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F8&lt;/b&gt;.
        /// </summary>
        internal static string btnAccept {
            get {
                return ResourceManager.GetString("btnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورتی كه فرم در حالت ویرایش حساب باشد ، اطلاعات ثبت می گردند.
        ///&lt;div&gt;&lt;/div&gt;در صورتی كه فرم در حالت نمایش حساب باشد ، به حالت ویرایش حساب خواهد رفت.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F3&lt;/b&gt;.
        /// </summary>
        internal static string btnAccountEditMode {
            get {
                return ResourceManager.GetString("btnAccountEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمانی برای نمایش بیمه های انتخاب شده ی مراجعه ی حساب جاری.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: Ctrl+W&lt;/b&gt;.
        /// </summary>
        internal static string btnAccountInsDetails {
            get {
                return ResourceManager.GetString("btnAccountInsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای بازپرداخت پول به بیمار بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F2&lt;/b&gt;.
        /// </summary>
        internal static string btnAccountPayMoney {
            get {
                return ResourceManager.GetString("btnAccountPayMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده و ویرایش جزئیات پرداخت یا بازپرداخت بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F2&lt;/b&gt;.
        /// </summary>
        internal static string btnAccountPayTypeDetails {
            get {
                return ResourceManager.GetString("btnAccountPayTypeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای دریافت پول از بیمار بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F1&lt;/b&gt;.
        /// </summary>
        internal static string btnAccountRecieveMoney {
            get {
                return ResourceManager.GetString("btnAccountRecieveMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمانی برای نمایش جزئیات اطلاعات قیمت های مراجعه ی حساب جاری.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: Ctrl+Q&lt;/b&gt;.
        /// </summary>
        internal static string btnAccountTotalData {
            get {
                return ResourceManager.GetString("btnAccountTotalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش دیاگرام دسترسی كاربران.
        ///با كلیك بر روی این دكمه ، دیاگرام گرافیكی سطوح دسترسی كاربران نمایش داده می شود..
        /// </summary>
        internal static string btnACLDiagram {
            get {
                return ResourceManager.GetString("btnACLDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن بانك به جدول.
        ///&lt;div&gt;&lt;/div&gt;با انتخاب این فرمان ، ردیف جدیدی برای افزودن بانك اضافه خواهد شده.
        ///&lt;div&gt;&lt;/div&gt;تا قبل از فشردن فرمان اعمال یا تایید ، بانك افزودن شده به سیستم اضافه نمی گردد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddAccountBank {
            get {
                return ResourceManager.GetString("btnAddAccountBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ثبت هزینه جدید به مراجعه جاری بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddAccountCost {
            get {
                return ResourceManager.GetString("btnAddAccountCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ثبت تخفیف جدید به مراجعه جاری بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F5&lt;/b&gt;.
        /// </summary>
        internal static string btnAddAccountDiscount {
            get {
                return ResourceManager.GetString("btnAddAccountDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن قالب قبض جدید.
        ///&lt;div&gt;&lt;/div&gt;برای افزودن یك قالب قبض جدید به لیست قالبها بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddBillTemplate {
            get {
                return ResourceManager.GetString("btnAddBillTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن كاربر مجاز جدید.
        ///&lt;div&gt;&lt;/div&gt;با فراخوانی این فرمان ، فرمی برای افزودن كاربر مجاز جدید به قالب قبض انتخاب شده نمایش داده میشود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddBillTemplateUser {
            get {
                return ResourceManager.GetString("btnAddBillTemplateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن یك  صندوق جدید به جدول.
        ///&lt;div&gt;&lt;/div&gt;با انتخاب این فرمان ، ردیف جدیدی برای افزودن صندوق نمایش داده خواهد شد.
        ///&lt;div&gt;&lt;/div&gt;تا قبل از فشردن فرمان اعمال یا تایید ، صندوق افزودن شده به بانك اضافه نمی گردند.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddCash {
            get {
                return ResourceManager.GetString("btnAddCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن یك  صندوقدار جدید.
        ///با انتخاب این فرمان ، فرمی برای افزودن صندوقدار نمایش داده خواهد شده.
        ///با انتخاب صندوقدار جدید ، امكان ثبت تراكنش در یك صندوق برای آن صندوقدار به وجود خواهد آمد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddCashCashier {
            get {
                return ResourceManager.GetString("btnAddCashCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن یك صندوقدار جدید.
        ///&lt;div&gt;&lt;/div&gt;با انتخاب این فرمان ، فرمی برای انتخاب كاربران به عنوان صندوقدار نمایش داده خواهد شد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddCashier {
            get {
                return ResourceManager.GetString("btnAddCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن یك نوع تخفیف یا هزینه جدید به جدول.
        ///با انتخاب این فرمان ، ردیف جدیدی برای افزودن یك نوع تخفیف یا هزینه افزوده خواهد شده.
        ///تا قبل از فشردن فرمان اعمال یا تایید ، نوع تخفیف یا هزینه افزودن شده به بانك اضافه نمی گردد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddCDTypes {
            get {
                return ResourceManager.GetString("btnAddCDTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه كردن كاربر ثبت كننده مدرك.
        ///&lt;div&gt;&lt;/div&gt;برای اضافه كردن یك كاربر به لیست كاربران مجاز ثبت كننده و ویرایش كننده مدرك ، بر روی این فرمان كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddDocumentor {
            get {
                return ResourceManager.GetString("btnAddDocumentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن گروه قالب جدید به سطح اول درخت قالب ها.
        ///گروه های قالب ها برای طبقه بندی كردن و آسان كردن دسترسی كاربران به قالب ها استفاده میشوند و حاوی متن قالب نمی باشند..
        /// </summary>
        internal static string btnAddDocumentRootGroup {
            get {
                return ResourceManager.GetString("btnAddDocumentRootGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن قالب  جدید به سطح اول درخت قالب ها.
        ///قالب ها برای آسان كردن ایجاد مدارك برای بیماران تعریف شده است.
        ///این قالب ها در هنگام ثبت یا ویرایش متن مدرك مراجعات بیماران مورد استفاده خواهد بود..
        /// </summary>
        internal static string btnAddDocumentRootTemplate {
            get {
                return ResourceManager.GetString("btnAddDocumentRootTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن طبقه بندی مدرك جدید.
        ///&lt;div&gt;&lt;/div&gt;با كلیك روی این دكمه ردیف جدیدی برای ثبت طبقه بندی مدرك نمایش داده می شود.
        ///&lt;div&gt;&lt;/div&gt;تا قبل از فشردن فرمان اعمال یا تایید ، طبقه بندی به بانك اضافه نمی گردد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddDocumentType {
            get {
                return ResourceManager.GetString("btnAddDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن گروه جدید.
        ///برای افزودن گروه كاربری جدید بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddGroup {
            get {
                return ResourceManager.GetString("btnAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن خدمت جدید به گروه خدمت.
        ///&lt;div&gt;&lt;/div&gt;برای افزودن خدمت جدید به گروه خدمت انتخاب شده بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddGroupsInServices {
            get {
                return ResourceManager.GetString("btnAddGroupsInServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن فرمول بیمه دوم جدید.
        ///برای افزودن فرمول بیمه دوم جدید بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddInsFormula {
            get {
                return ResourceManager.GetString("btnAddInsFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن فرمول به متن فرمول بیمه.
        ///با فراخوانی این فرمان متن فرمول ریاضی سرفصل انتخاب شده به متن كلی اضافه می شود..
        /// </summary>
        internal static string btnAddInsFormulaToText {
            get {
                return ResourceManager.GetString("btnAddInsFormulaToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن بیمه جدید به سیستم.
        ///&lt;div&gt;&lt;/div&gt;برای افزودن بیمه مراجعه جدید به سیستم بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddInsurances {
            get {
                return ResourceManager.GetString("btnAddInsurances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن &quot;فیلد اطلاعاتی اضافی بیماران&quot;.
        ///&lt;div&gt;&lt;/div&gt;با انتخاب این فرمان ، فرمی برای افزودن فیلدی جدید نمایش داده خواهد شد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddPatAddinData {
            get {
                return ResourceManager.GetString("btnAddPatAddinData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن شهر جدید.
        ///&lt;div&gt;&lt;/div&gt;با كلیك روی این دكمه می توانید یك شهر جدید تبت نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddPatCity {
            get {
                return ResourceManager.GetString("btnAddPatCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن كشور جدید.
        ///&lt;div&gt;&lt;/div&gt;با كلیك روی این دكمه می توانید یك كشور جدید تبت نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddPatCountries {
            get {
                return ResourceManager.GetString("btnAddPatCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن نام جدید به جدول.
        ///&lt;div&gt;&lt;/div&gt;با انتخاب این فرمان ، ردیفی برای افزودن نام جدید در جدول نمایش داده خواهد شد.
        ///&lt;div&gt;&lt;/div&gt;تا قبل از فشردن فرمان اعمال یا انصراف ، ردیف افزوده شده به بانك اضافه نمی گردد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddPatientName {
            get {
                return ResourceManager.GetString("btnAddPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن شغل جدید.
        ///&lt;div&gt;&lt;/div&gt;با كلیك بر روی این دكمه ردیف جدیدی برای افزودن شغل جدید نمایش دااده می شود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddPatJob {
            get {
                return ResourceManager.GetString("btnAddPatJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن استان جدید.
        ///&lt;div&gt;&lt;/div&gt;برای افزودن استان جدید بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddPatStates {
            get {
                return ResourceManager.GetString("btnAddPatStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن &quot;فیلد اطلاعاتی اضافی مراجعات&quot;.
        ///&lt;div&gt;&lt;/div&gt;با انتخاب این فرمان ، فرمی برای افزودن فیلدی جدید نمایش داده خواهد شد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddRefAddinData {
            get {
                return ResourceManager.GetString("btnAddRefAddinData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن كاربر پذیرش كننده جدید.
        ///&lt;div&gt;&lt;/div&gt;برای افزودن یك كاربر به لیست كاربران پذیرش كننده بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddRefAdmitter {
            get {
                return ResourceManager.GetString("btnAddRefAdmitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن انجام دهنده جدید.
        ///&lt;div&gt;&lt;/div&gt;برای افزودن متخصص جدید بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddRefPerformers {
            get {
                return ResourceManager.GetString("btnAddRefPerformers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن پزشك مراجعه جدید.
        ///&lt;div&gt;&lt;/div&gt;برای افزودن پزشك مراجعه جدید بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddRefPhys {
            get {
                return ResourceManager.GetString("btnAddRefPhys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن پزشك مراجعه جدید.
        ///&lt;div&gt;&lt;/div&gt;با فراخوانی این فرمان ، فرمی برای افزودن پزشك مراجعه جدید نمایش داده خواهد شد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: Ctrl+T&lt;/b&gt;.
        /// </summary>
        internal static string btnAddRefPhysician {
            get {
                return ResourceManager.GetString("btnAddRefPhysician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن تخصص پزشك  جدید.
        ///&lt;div&gt;&lt;/div&gt;با كلیك این فرمان می توانید یك تخصص  جدید وارد نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddRefPhysSpecs {
            get {
                return ResourceManager.GetString("btnAddRefPhysSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن وضعیت مراجعه جدید.
        ///&lt;div&gt;&lt;/div&gt;برای افزودن وضعیت مراجعه جدید به جدول بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddRefStatus {
            get {
                return ResourceManager.GetString("btnAddRefStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن فیلد اطلاعات اضافی.
        ///&lt;div&gt;&lt;/div&gt;با كلیك بر روی این دكمه فرم افزودن فیلد اطلاعات اضافه برای برنامه های نوبت دهی نمایش دااده می شود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddSchAddinData {
            get {
                return ResourceManager.GetString("btnAddSchAddinData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن برنامه جدید.
        ///&lt;div&gt;&lt;/div&gt;با كلیك بر روی این دكمه فرم افزودن برنامه نمایش داده می شود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddSchApps {
            get {
                return ResourceManager.GetString("btnAddSchApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن كاربر نوبت دهنده جدید.
        ///&lt;div&gt;&lt;/div&gt;برای افزودن كاربر جدید به لیست كاربران مجاز نوبت دهنده بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddSchedulder {
            get {
                return ResourceManager.GetString("btnAddSchedulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد یك روز تعطیل جدید برای یك برنامه نوبت دهی.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddSchHoliday {
            get {
                return ResourceManager.GetString("btnAddSchHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن خدمت جدید.
        ///&lt;div&gt;&lt;/div&gt;برای افزودن خدمت این فرمان را فشار دهید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddService {
            get {
                return ResourceManager.GetString("btnAddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن طبقه بندی جدید.
        ///&lt;div&gt;&lt;/div&gt;با كلیك روی این دكمه می توانید یك طبقه بندی جدید تبت نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddServiceCat {
            get {
                return ResourceManager.GetString("btnAddServiceCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن كادر درمان پیش فرض جدید برای خدمات.
        ///&lt;div&gt;&lt;/div&gt;برای افزودن پیش فرض جدید بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddServicesDefaultPerformer {
            get {
                return ResourceManager.GetString("btnAddServicesDefaultPerformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن گروه خدمت جدید.
        ///&lt;div&gt;&lt;/div&gt;برای افزودن گروه خدمت این فرمان را فشار دهید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddServicesGroups {
            get {
                return ResourceManager.GetString("btnAddServicesGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن فیلد قیمت خدمت جدید.
        ///&lt;div&gt;&lt;/div&gt;برای افزودن فیلد بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddServicesPriceField {
            get {
                return ResourceManager.GetString("btnAddServicesPriceField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن كاربر جدید.
        ///&lt;div&gt;&lt;/div&gt;برای افزودن كاربر جدید بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F6&lt;/b&gt;.
        /// </summary>
        internal static string btnAddUser {
            get {
                return ResourceManager.GetString("btnAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب تمام ردیف های موجود در لیست.
        ///با فراخوانی این فرمان كلیه ردیف های موجود در جدول انتخاب می گردند..
        /// </summary>
        internal static string btnAll {
            get {
                return ResourceManager.GetString("btnAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمال تنظیمات و ادامه مدیریت اطلاعات.
        ///&lt;div&gt;&lt;/div&gt;پس از فشردن این كلید تنظیمات در بانك اطلاعاتی ذخیره می گردد اما فرم بسته نمیشود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F4&lt;/b&gt;.
        /// </summary>
        internal static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد فایل پشتیبانی از بانك اطلاعات ، بر اساس تنظیمات صورت گرفته.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F8&lt;/b&gt;.
        /// </summary>
        internal static string btnBackup {
            get {
                return ResourceManager.GetString("btnBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیم محدودیت ها و دسترسی های كاربران به قبوض.
        ///برای تنظیم مجوزهای كاربران برای قالب های قبوض بر روی این دكمه كلیك نمایید..
        /// </summary>
        internal static string btnBillTemplatesAccess {
            get {
                return ResourceManager.GetString("btnBillTemplatesAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج از فرم.
        ///&lt;div&gt;&lt;/div&gt;در صورت اجرای این فرمان ، بدون ذخیره سازی اطلاعات از آخرین اعمال ، فرم بسته می شود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: ESC&lt;/b&gt;.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج از فرم.
        ///&lt;div&gt;&lt;/div&gt;در صورت اجرای این فرمان ، بدون ذخیره سازی اطلاعات فرم بسته می شود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: ESC&lt;/b&gt;.
        /// </summary>
        internal static string btnCancel_NoApply {
            get {
                return ResourceManager.GetString("btnCancel_NoApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمان بستن صندوق.
        ///با بستن صندوق انتخاب شده ، تا زمانی كه صندوق مجدداً باز نگردد ، امكان ثبت تراكنش در صندوق مورد نظر وجود ندارد..
        /// </summary>
        internal static string btnCashCloseCash {
            get {
                return ResourceManager.GetString("btnCashCloseCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با فراخوانی این فرمان ، گزارشی از ورود و خروج های پول در صندوق مورد نظر ، از آخرین زمانی كه مجدداً باز شده نمایش داده خواهد شد..
        /// </summary>
        internal static string btnCashInOutReport {
            get {
                return ResourceManager.GetString("btnCashInOutReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمان ورود پول به صندوق.
        ///با فراخوانی این فرمان فرمی برای وارد كردن پول به صندوق نمایش داده می شود..
        /// </summary>
        internal static string btnCashInput {
            get {
                return ResourceManager.GetString("btnCashInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمان باز كردن صندوق.
        ///با بازكردن صندوق انتخاب شده ، امكان ثبت تراكنش در صندوق مورد نظر وجود خواهد داشت..
        /// </summary>
        internal static string btnCashOpenCash {
            get {
                return ResourceManager.GetString("btnCashOpenCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمان خروج پول از صندوق.
        ///با فراخوانی این فرمان فرمی برای خارج كردن پول از صندوق نمایش داده می شود..
        /// </summary>
        internal static string btnCashOutput {
            get {
                return ResourceManager.GetString("btnCashOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای نمایش فرم گزارش صندوق ها روی دكمه كلیك  نمایید.
        ///فرم گزارش های صندوق ، وضعیتی از صندوق های فعال در سیستم نمایش می دهد..
        /// </summary>
        internal static string btnCashReport {
            get {
                return ResourceManager.GetString("btnCashReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج از فرم.
        ///&lt;div&gt;&lt;/div&gt;در صورت اجرای این فرمان ، فرم بسته می شود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: ESC&lt;/b&gt;.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كپی برداری تنظیمات بیمه ها.
        ///با فراخوانی این فرمان ، فرمی برای كپی برداری تنظیمات یك بیمه ، به سایر بیمه ها نمایش داده خواهد شد..
        /// </summary>
        internal static string btnCopyInsuranceSettings {
            get {
                return ResourceManager.GetString("btnCopyInsuranceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كپی برداری دسترسی های كاربران.
        ///در صورت اجرا این فرمان سطوح دسترسی یك كاربر به كاربران انتخاب شده ، عیناً كپی خواهد شد..
        /// </summary>
        internal static string btnCopyUserACL {
            get {
                return ResourceManager.GetString("btnCopyUserACL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف ردیف انتخاب شده از جدول.
        ///&lt;div&gt;&lt;/div&gt;با تایید این فرمان ، ردیف انتخاب شده از جدول حذف میگردد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: DEL&lt;/b&gt;
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;تذكر:&lt;/b&gt;
        ///&lt;div&gt;&lt;/div&gt;در صورت حذف ردیف ، تنها زمانی تغییرات اعمال می گردد كه فرمان اعمال یا تایید فراخوانی گردند..
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف ردیف انتخاب شده از جدول.
        ///&lt;div&gt;&lt;/div&gt;با تایید این فرمان ، ردیف انتخاب شده از جدول حذف میگردد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: DEL&lt;/b&gt;.
        /// </summary>
        internal static string btnDelete_NoSubmit {
            get {
                return ResourceManager.GetString("btnDelete_NoSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ایجاد فایل خروجی با فرمت های مختلف بر روی این دكمه كلیك نمایید..
        /// </summary>
        internal static string btnDesignedReportExport {
            get {
                return ResourceManager.GetString("btnDesignedReportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با فراخوانی این فرمان ، بر اساس فیلترهایی كه تنظیم نموده اید ، گزارش مورد نظر شما تولید می شود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F8&lt;/b&gt;.
        /// </summary>
        internal static string btnDesignedReportGenerate {
            get {
                return ResourceManager.GetString("btnDesignedReportGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای بازخوانی مجدد این گزارش بر روی این دكمه كلیك نمایید..
        /// </summary>
        internal static string btnDesignedReportRefreshReport {
            get {
                return ResourceManager.GetString("btnDesignedReportRefreshReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره سازی مدرك جاری.
        ///&lt;div&gt;&lt;/div&gt;در صورت فراخوانی این فرمان ، مدرك جاری ذخیره می گردد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;توجه:&lt;/b&gt;
        ///&lt;div&gt;&lt;/div&gt;با فراخوانی این فرمان فرم بسته نمی شود..
        /// </summary>
        internal static string btnDocSave {
            get {
                return ResourceManager.GetString("btnDocSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب قالب های پیش فرض مدرك.
        ///با فراخوانی این فرمان ، لیستی از قالب های پیش فرض مدرك ثبت شده در بخش تنظیمات نمایش داده خواهد شد.
        ///پس از انتخاب یك قالب مدرك ، متن مدرك جاری حذف شده و متن قالب انتخاب شده جایگزین میشود..
        /// </summary>
        internal static string btnDocTemplates {
            get {
                return ResourceManager.GetString("btnDocTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن مدرك جدید.
        ///&lt;div&gt;&lt;/div&gt;برای افزودن مدرك جدید به مراجعه ی جاری بر روی این دكمه كلیك كنید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F4&lt;/b&gt;.
        /// </summary>
        internal static string btnDocumentNewDoc {
            get {
                return ResourceManager.GetString("btnDocumentNewDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش سطح دسترسی.
        ///با كلیك این دكمه می توانید دسترسی كاربر یا گروه  انتخاب شده را تغییر دهید..
        /// </summary>
        internal static string btnEditAccess {
            get {
                return ResourceManager.GetString("btnEditAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اطلاعات بیمه.
        ///&lt;div&gt;&lt;/div&gt;
        ///با فراخوانی این فرمان ، فرمی برای ویرایش اطلاعات پایه بیمه انتخاب شده نمایش داده میشود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F2&lt;/b&gt;.
        /// </summary>
        internal static string btnEditIns {
            get {
                return ResourceManager.GetString("btnEditIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش پزشك مراجعه انتخاب شده.
        ///&lt;div&gt;&lt;/div&gt;با فراخوانی این فرمان ، فرمی برای ویرایش پزشك مراجعه انتخاب شده نمایش داده میشود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: Ctrl+R&lt;/b&gt;.
        /// </summary>
        internal static string btnEditRefPhysician {
            get {
                return ResourceManager.GetString("btnEditRefPhysician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ایجاد خروجی از گزارش در برنامه اكسل بر روی این دكمه كلیك نمایید..
        /// </summary>
        internal static string btnExportReportToExcel {
            get {
                return ResourceManager.GetString("btnExportReportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمانی برای آزاد سازی حساب قفل شده.
        ///در صورتی كه حساب مراجعه ای توسط كاربر دیگری قفل شده و مایلید كه قفل را آزاد نمایید ، این فرمان را فراخوانی نمایید.
        ///توجه نمایید كه این فرمان تنها زمانی مفید خواهد بود كه بر اثر خطای سیستم ، حساب بدون علت قفل شده است.
        ///در صورتی كه حساب جاری توسط كاربر دیگری در حال ویرایش است از فراخوانی این فرمان خودداری كنید..
        /// </summary>
        internal static string btnFreeAccount {
            get {
                return ResourceManager.GetString("btnFreeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یرای مشاهده و تغییر تنظیمات چاپگر بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F4&lt;/b&gt;.
        /// </summary>
        internal static string btnGridPrintingPrinterSettings {
            get {
                return ResourceManager.GetString("btnGridPrintingPrinterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای تنظیم ساختار صفحات گزارش بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F4&lt;/b&gt;.
        /// </summary>
        internal static string btnGridPrintingPrintSettings {
            get {
                return ResourceManager.GetString("btnGridPrintingPrintSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش آموزش كاربری فرم.
        ///&lt;div&gt;&lt;/div&gt;این راهنمای كاربری به شما در مورد نحوه عملكرد فرم كمك می نماید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F1&lt;/b&gt;.
        /// </summary>
        internal static string btnHelp {
            get {
                return ResourceManager.GetString("btnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محاسبه خودكار قیمت های خدمات بیمه انتخاب شده.
        ///با فراخوانی این فرمان ، فرمی برای محاسبه خودكار و جمعی قیمت های بیمه انتخاب شده نمایش داده میشود..
        /// </summary>
        internal static string btnInsAutoCalculation {
            get {
                return ResourceManager.GetString("btnInsAutoCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با فراخوانی این فرمان ، فرمول بیمه دوم وارد شده ، بر اساس تعدادی عدد آزمایشی وارد شده توسط كاربر بررسی و محاسبه می گردد..
        /// </summary>
        internal static string btnInsFormulaValidation {
            get {
                return ResourceManager.GetString("btnInsFormulaValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم مدیریت بیمه های دوم.
        ///با فراخوانی این فرمان ، فرمی برای مدیریت فرمول های بیمه دوم نمایش داده خواهد شد..
        /// </summary>
        internal static string btnManageIns2Formulas {
            get {
                return ResourceManager.GetString("btnManageIns2Formulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد دسترسی جدید.
        ///با كلیك این دكمه می توانید برای سطح دسترسی انتخاب شده ، دسترسی جدیدی برای كاربران یا گروه ها ایجاد كنید..
        /// </summary>
        internal static string btnNewAccess {
            get {
                return ResourceManager.GetString("btnNewAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت مراجعه بیمار جدید.
        ///&lt;div&gt;&lt;/div&gt;در صورتی كه فرم در حالت ثبت یا ویرایش مراجعه ی یك بیمار باشد ، پس از ثبت بیمار و مراجعه ، فرم به حالت ثبت بیمار جدید خواهد رفت.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F2&lt;/b&gt;.
        /// </summary>
        internal static string btnNewPatRef {
            get {
                return ResourceManager.GetString("btnNewPatRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده اطلاعات مراجعه بعدی بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F10&lt;/b&gt;.
        /// </summary>
        internal static string btnNextReferral {
            get {
                return ResourceManager.GetString("btnNextReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف انتخاب تمام ردیف های موجود در لیست.
        ///با فراخوانی این فرمان كلیه ردیف های موجود در جدول به انتخاب نشده تبدیل می گردند..
        /// </summary>
        internal static string btnNone {
            get {
                return ResourceManager.GetString("btnNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده فرم اطلاعات اضافه بیمار بر روی این دكمه كلیك نمایید..
        /// </summary>
        internal static string btnPatAddInData {
            get {
                return ResourceManager.GetString("btnPatAddInData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای حذف بیمار انتخاب شده بر روی این دكمه كلیك نمایید.
        ///با حذف بیمار ، كلیه اطلاعات پرونده بیمار حذف شده و امكان بازگشت وجود نخواهد داشت.
        ///این اطلاعات شامل اطلاعات بیمار ، مراجعات بیمار ، خدمات مراجعات ، اطلاعات مالی حساب مراجعات و مدارك مراجعات می باشد..
        /// </summary>
        internal static string btnPatDeletePatient {
            get {
                return ResourceManager.GetString("btnPatDeletePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده اطلاعات كامل بیمار بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: Ctrl+Q&lt;/b&gt;.
        /// </summary>
        internal static string btnPatDetailsData {
            get {
                return ResourceManager.GetString("btnPatDetailsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورتی كه فرم در حالت ثبت یا ویرایش بیمار باشد ، اطلاعات ثبت می گردند.
        ///&lt;div&gt;&lt;/div&gt;در صورتی كه فرم در حالت نمایش بیمار باشد ، به حالت ویرایش بیمار خواهد رفت.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F3&lt;/b&gt;.
        /// </summary>
        internal static string btnPatEditPatient {
            get {
                return ResourceManager.GetString("btnPatEditPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای افزودن بیمار جدید بر روی این دكمه كلیك نمایید.
        ///در صورتی كه در حال ثبت یا ویرایش یك بیمار باشید ، پس از دریافت تایید شما ، فرم به حالت ثبت بیمار جدید خواهد رفت.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F2&lt;/b&gt;.
        /// </summary>
        internal static string btnPatFormNewPatient {
            get {
                return ResourceManager.GetString("btnPatFormNewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای افزودن مراجعه جدید بر روی این دكمه كلیك نمایید.
        ///در صورتی كه در حال ثبت یا ویرایش یك بیمار باشید ، پس از دریافت تایید شما ، بیمار ثبت شده و فرم ثبت مراجعه جدید برای بیمار نمایش داده خواهد شد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F4&lt;/b&gt;.
        /// </summary>
        internal static string btnPatFormNewRef {
            get {
                return ResourceManager.GetString("btnPatFormNewRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمانی برای آزاد سازی بیماران قفل شده.
        ///در صورتی كه بیماری توسط كاربر دیگری قفل شده و مایلید كه قفل را آزاد نمایید ، این فرمان را فراخوانی نمایید.
        ///توجه نمایید كه این فرمان تنها زمانی مفید خواهد بود كه بر اثر خطای سیستم ، بیمار بدون علت قفل شده است.
        ///در صورتی كه بیمار جاری توسط كاربر دیگری در حال ویرایش است از فراخوانی این فرمان خودداری كنید..
        /// </summary>
        internal static string btnPatFreePat {
            get {
                return ResourceManager.GetString("btnPatFreePat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده اطلاعات بیمار بعدی بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;در صورتی كه در حال ثبت یا ویرایش یك بیمار باشید ، ابتدا در این مورد از شما پرسش خواهد شد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F12&lt;/b&gt;.
        /// </summary>
        internal static string btnPatNextPatient {
            get {
                return ResourceManager.GetString("btnPatNextPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده اطلاعات بیمار قبلی بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;در صورتی كه در حال ثبت یا ویرایش یك بیمار باشید ، ابتدا در این مورد از شما پرسش خواهد شد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F11&lt;/b&gt;.
        /// </summary>
        internal static string btnPatPrevPatient {
            get {
                return ResourceManager.GetString("btnPatPrevPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده اطلاعات مراجعه قبلی بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F9&lt;/b&gt;.
        /// </summary>
        internal static string btnPrevReferral {
            get {
                return ResourceManager.GetString("btnPrevReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چاپ جدول .
        ///با فراخوانی این فرمان ، فرمی برای مدیریت چاپ جدول نمایش داده خواهد شد..
        /// </summary>
        internal static string btnPrint {
            get {
                return ResourceManager.GetString("btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای پیش نمایش چاپ قبض انتخاب شده برای مراجعه جاری بر روی این دكمه كلیك نمایید..
        /// </summary>
        internal static string btnPrintPreviewRefBill {
            get {
                return ResourceManager.GetString("btnPrintPreviewRefBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای چاپ قبض انتخاب شده برای مراجعه جاری بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F8&lt;/b&gt;.
        /// </summary>
        internal static string btnPrintRefBill {
            get {
                return ResourceManager.GetString("btnPrintRefBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای چاپ گزارش تهیه شده بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F8&lt;/b&gt;.
        /// </summary>
        internal static string btnPrintReport {
            get {
                return ResourceManager.GetString("btnPrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازسازی ساختار بانك اطلاعاتی جهت بالا بردن سرعت و كیفیت ارتباط با اطلاعات.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F8&lt;/b&gt;.
        /// </summary>
        internal static string btnRebuildDb {
            get {
                return ResourceManager.GetString("btnRebuildDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت پول برای مراجعه ی بیمار انتخاب شده.
        ///&lt;div&gt;&lt;/div&gt;با فراخوانی این فرمان ، فرمی برای دریافت پول برای مراجعه ی بیمار انتخاب شده نمایش داده می شود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F8 یا Enter&lt;/b&gt;.
        /// </summary>
        internal static string btnRecieveMoney {
            get {
                return ResourceManager.GetString("btnRecieveMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده فرم حساب این مراجعه ی بیمار بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F4&lt;/b&gt;.
        /// </summary>
        internal static string btnRefAccount {
            get {
                return ResourceManager.GetString("btnRefAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده فرم اطلاعات اضافه مراجعه این بیمار بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: Ctrl+W&lt;/b&gt;.
        /// </summary>
        internal static string btnRefAddInData {
            get {
                return ResourceManager.GetString("btnRefAddInData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده فرم مدارك مراجعه جاری این بیمار بر روی این دكمه كلیك نمایید..
        /// </summary>
        internal static string btnRefDocuments {
            get {
                return ResourceManager.GetString("btnRefDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورتی كه فرم در حالت ثبت یا ویرایش مراجعه باشد ، اطلاعات ثبت می گردند.
        ///&lt;div&gt;&lt;/div&gt;در صورتی كه فرم در حالت نمایش مراجعه باشد ، به حالت ویرایش مراجعه خواهد رفت.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F3&lt;/b&gt;.
        /// </summary>
        internal static string btnRefEditRef {
            get {
                return ResourceManager.GetString("btnRefEditRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمانی برای آزاد سازی مراجعه قفل شده.
        ///در صورتی كه مراجعه بیماری توسط كاربر دیگری قفل شده و مایلید كه قفل را آزاد نمایید ، این فرمان را فراخوانی نمایید.
        ///توجه نمایید كه این فرمان تنها زمانی مفید خواهد بود كه بر اثر خطای سیستم ، مراجعه بدون علت قفل شده است.
        ///در صورتی كه مراجعه جاری توسط كاربر دیگری در حال ویرایش است از فراخوانی این فرمان خودداری كنید..
        /// </summary>
        internal static string btnRefFreeRef {
            get {
                return ResourceManager.GetString("btnRefFreeRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده اطلاعات كامل تنظیمات بیمه انتخاب شده بر روی این دكمه كلیك نمایید..
        /// </summary>
        internal static string btnRefInsDetails {
            get {
                return ResourceManager.GetString("btnRefInsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای افزودن مراجعه جدید به پرونده بیمار جاری بر روی این دكمه كلیك نمایید.
        ///در صورتی كه در حال ثبت یا ویرایش یك مراجعه بیمار باشید ، پس از دریافت تایید شما ، فرم به حالت ثبت مراجعه جدید خواهد رفت.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F2&lt;/b&gt;.
        /// </summary>
        internal static string btnRefNewRef {
            get {
                return ResourceManager.GetString("btnRefNewRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادغام پزشكان.
        ///با فراخوانی این فرمان ، فرمی برای ادغام اطلاعات و مراجعات ثبت شده چند پزشك در یك پزشك نمایش داده خواهد شد..
        /// </summary>
        internal static string btnRefPhysMixRows {
            get {
                return ResourceManager.GetString("btnRefPhysMixRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;&lt;/div&gt;برای به روز رسانی اطلاعات این صفحه بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F5&lt;/b&gt;.
        /// </summary>
        internal static string btnRefresh {
            get {
                return ResourceManager.GetString("btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای انتخاب خدمت برای مراجعه بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F7&lt;/b&gt;.
        /// </summary>
        internal static string btnRefServiceSelection {
            get {
                return ResourceManager.GetString("btnRefServiceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف دسترسی سطح انتخاب شده.
        ///با كلیك بر روی این دكمه می توانید دسترسی گروه یا كاربر انتخاب شده را حذف كنید.
        ///با حذف دسترسی ، در واقع به كاربر یا گروه دسترسی لازم برای كار با سطح مورد نظر را ارائه داده اید..
        /// </summary>
        internal static string btnRemoveAccess {
            get {
                return ResourceManager.GetString("btnRemoveAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف اطلاعات مراجعات بیماران بر اساس تاریخ مراجعه نعریف شده.
        ///با حذف اطلاعات یك مراجعه ، كلیه اطلاعات پرونده آن مراجعه نیز حذف می گردد.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F8&lt;/b&gt;.
        /// </summary>
        internal static string btnRemoveData {
            get {
                return ResourceManager.GetString("btnRemoveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای تغییر اندازه و نوع قلم گزارش بر روی این دكمه كلیك نمایید..
        /// </summary>
        internal static string btnReportEditFont {
            get {
                return ResourceManager.GetString("btnReportEditFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده اولین صفحه این گزارش بر روی این دكمه كلیك نمایید..
        /// </summary>
        internal static string btnReportFirstPage {
            get {
                return ResourceManager.GetString("btnReportFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده آخرین صفحه این گزارش بر روی این دكمه كلیك نمایید..
        /// </summary>
        internal static string btnReportLastPage {
            get {
                return ResourceManager.GetString("btnReportLastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده صفحه بعدی این گزارش بر روی این دكمه كلیك نمایید..
        /// </summary>
        internal static string btnReportNextPage {
            get {
                return ResourceManager.GetString("btnReportNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای نمایش ظاهر قطعی گزارش قبل از چاپ بر روی این دكمه كلیك نمایید.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F8&lt;/b&gt;.
        /// </summary>
        internal static string btnReportPreviewView {
            get {
                return ResourceManager.GetString("btnReportPreviewView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده صفحه قبلی این گزارش بر روی این دكمه كلیك نمایید..
        /// </summary>
        internal static string btnReportPrevPage {
            get {
                return ResourceManager.GetString("btnReportPrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی اطلاعات بانك اطلاعاتی از فایل پشتیبانی تولید شده توسط برنامه ، بر اساس تنظیمات صورت گرفته.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F8&lt;/b&gt;.
        /// </summary>
        internal static string btnRestore {
            get {
                return ResourceManager.GetString("btnRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن نوبت به برنامه انتخاب شده.
        ///با كلیك بر روی این دكمه یك ردیف نوبت جدید به جدول نوبت ها اضافه می شود..
        /// </summary>
        internal static string btnSchAddAppointment {
            get {
                return ResourceManager.GetString("btnSchAddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد های اضافه برنامه های نوبت دهی.
        ///با كلیك روی این دكمه فرم اطلاعات اضافه برنامه های نوبت دهی نمایش داده می شود.
        /// </summary>
        internal static string btnSchAddinFields {
            get {
                return ResourceManager.GetString("btnSchAddinFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی وضعیت برنامه نوبت دهی.
        ///&lt;div&gt;&lt;/div&gt;پس از فشردن این كلید ، بر اساس تنظیمات صورت گرفته ،وضعیت برنامه های نوبت دهی نمایش داده می شود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F4&lt;/b&gt;.
        /// </summary>
        internal static string btnSchAppSearch {
            get {
                return ResourceManager.GetString("btnSchAppSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی نوبت بیماران.
        ///&lt;div&gt;&lt;/div&gt;با كلیك بر روی این دكمه فرمی برای جستجوی نوبت های بیماران ثبت شده در سیستم را مشاهده خواهید نمود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F7&lt;/b&gt;.
        /// </summary>
        internal static string btnSchFindPatientSchedule {
            get {
                return ResourceManager.GetString("btnSchFindPatientSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت روزهای تعطیل برنامه های نوبت دهی.
        ///با كلیك روی این دكمه فرم مدیریت روزهای تعطیل برنامه های نوبت دهی نمایش داده می شود..
        /// </summary>
        internal static string btnSchHolidays {
            get {
                return ResourceManager.GetString("btnSchHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش روز بعدی برنامه نوبت دهی جاری.
        ///&lt;div&gt;&lt;/div&gt;در صورت اجرای این فرمان ، روز جاری به روز بعدی منتفل می شود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: Ctrl+Q&lt;/b&gt;.
        /// </summary>
        internal static string btnSchNextShift {
            get {
                return ResourceManager.GetString("btnSchNextShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی بیماران نوبت داده شده در برنامه نوبتدهی.
        ///&lt;div&gt;&lt;/div&gt;پس از فشردن این كلید ، بر اساس تنظیمات صورت گرفته ، نوبت های ثبت شده برای بیماران نمایش داده می شود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F4&lt;/b&gt;.
        /// </summary>
        internal static string btnSchPatSearch {
            get {
                return ResourceManager.GetString("btnSchPatSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب نوبت انتخاب شده.
        ///&lt;div&gt;&lt;/div&gt;پس از فشردن این كلید فرم بسته شده و نوبت مورد نظر نمایش داده می شود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F8&lt;/b&gt;.
        /// </summary>
        internal static string btnSchPatSearchSelect {
            get {
                return ResourceManager.GetString("btnSchPatSearchSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش روز قبلی برنامه نوبت دهی جاری.
        ///&lt;div&gt;&lt;/div&gt;در صورت اجرای این فرمان ، روز جاری به روز قبلی منتفل می شود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: Ctrl+W&lt;/b&gt;.
        /// </summary>
        internal static string btnSchPrevShift {
            get {
                return ResourceManager.GetString("btnSchPrevShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی وضعیت برنامه نوبت دهی.
        ///&lt;div&gt;&lt;/div&gt;با كلیك بر روی این فرمان فرم جستجوی وضعیت برنامه های سیستم را مشاهده خواهید نمود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: Ctrl+S&lt;/b&gt;.
        /// </summary>
        internal static string btnSchSearchFreeSchedule {
            get {
                return ResourceManager.GetString("btnSchSearchFreeSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب برنامه نوبت دهی انتخاب شده در روز مورد نظر.
        ///&lt;div&gt;&lt;/div&gt;پس از فشردن این كلید فرم بسته شده و برنامه مورد نظر نمایش داده می شود.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F8&lt;/b&gt;.
        /// </summary>
        internal static string btnSchSelectApp {
            get {
                return ResourceManager.GetString("btnSchSelectApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش ساختار برنامه.
        ///با كلیك بر روی این دكمه فرمی كه شامل اطلاعات كامل ساختار برنامه است نمایش داده خواهد شد..
        /// </summary>
        internal static string btnSchShowProgramDetails {
            get {
                return ResourceManager.GetString("btnSchShowProgramDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت سرفصل های خدمات.
        ///با فراخوانی این فرمان ، فرمی برای مدیریت سرفصل های قیمت خدمات ، از جمله افزودن ، ویرایش یا حذف سرفصل خدمت نمایش داده خواهد شد..
        /// </summary>
        internal static string btnServiceColumns {
            get {
                return ResourceManager.GetString("btnServiceColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر گروهی قیمت خدمات.
        ///با فراخوانی این فرمان ، فرمی برای اعمال تغییرات دسته جمعی بین خدمات مختلف به صورت گروهی نمایش داده خواهد شد..
        /// </summary>
        internal static string btnServicesChangeAll {
            get {
                return ResourceManager.GetString("btnServicesChangeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر كلمه عبور.
        ///با كلیك بر روی این دكمه فرم تغییر كلمه عبور را مشاهده خواهید كرد..
        /// </summary>
        internal static string btnUsersResetPassword {
            get {
                return ResourceManager.GetString("btnUsersResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست انتخاب بانك از میان  بانك های  ثبت شده در سیستم..
        /// </summary>
        internal static string cboBankName {
            get {
                return ResourceManager.GetString("cboBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست انتخاب صندوق از صندوق های ثبت شده در سیستم..
        /// </summary>
        internal static string cboCash {
            get {
                return ResourceManager.GetString("cboCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش مراجعات با پزشك انتخاب شده.
        ///با فراخوانی این فرمان ، تنها مراجعاتی نمایش داده خواهد شد كه حداقل یكی از خدمات آنها با پزشك انتخاب شده ثبت شده باشند..
        /// </summary>
        internal static string cboDocMonitorPhysician {
            get {
                return ResourceManager.GetString("cboDocMonitorPhysician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش مراجعات با طبقه بندی خدمت انتخاب شده.
        ///با فراخوانی این فرمان ، تنها مراجعاتی نمایش داده خواهد شد كه حداقل یكی از خدمات آنها در طبقه بندی انتخاب شده باشند..
        /// </summary>
        internal static string cboDocMonitorServiceCat {
            get {
                return ResourceManager.GetString("cboDocMonitorServiceCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست انتخاب گروه خدمت برای مدیریت خدماتی كه تحت پوشش آن گروه هستند.
        ///با تغییر گروه مورد نظر ، جدول خدمات تحت پوشش بر اساس آن گروه تغییر می كند..
        /// </summary>
        internal static string cboGroupsServices {
            get {
                return ResourceManager.GetString("cboGroupsServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست پارامتر های قابل استفاده برای فرمول بیمه دوم..
        /// </summary>
        internal static string cboInsParamFormula {
            get {
                return ResourceManager.GetString("cboInsParamFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست انتخاب قالب قبض از میان قالب های قبض ثبت شده در سیستم..
        /// </summary>
        internal static string cboPrintTemplates {
            get {
                return ResourceManager.GetString("cboPrintTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب برنامه نوبت دهی مورد نظر از میان برنامه هایی كه در سیستم ثبت شده اند.
        ///&lt;div&gt;&lt;/div&gt;&lt;b&gt;كلید میانبر: F12&lt;/b&gt;.
        /// </summary>
        internal static string cboSchPrograms {
            get {
                return ResourceManager.GetString("cboSchPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست انتخاب نوع طبقه بندی خدمات برای افزودن خدماتی كه تحت پوشش آن طبقه بندی هستند.
        ///با تغییر طبقه بندی مورد نظر ، جدول خدمات بر اساس آن طبقه بندی تغییر می كند..
        /// </summary>
        internal static string cboServiceCategory {
            get {
                return ResourceManager.GetString("cboServiceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست انتخاب گروه مورد نظر برای مدیریت كاربرانی كه عضو آن گروه هستند.
        ///با تغییر گروه مورد نظر ، جدول كاربران عضو گروه بر اساس آن گروه تغییر می كند..
        /// </summary>
        internal static string cboUsersGroups {
            get {
                return ResourceManager.GetString("cboUsersGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش مراجعات فاقد خدمت.
        ///در صورت انتخاب این گزینه ،مراجعاتی كه هیچ خدمتی برای آنها ثبت نشده باشد نیز نمایش داده می شوند..
        /// </summary>
        internal static string cBoxDocMonitorShowNoServiceRefs {
            get {
                return ResourceManager.GetString("cBoxDocMonitorShowNoServiceRefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش بانك های غیر فعال شده.
        ///در صورتی كه یك بانك غیر فعال گردد ، امكان ثبت تراكنشی با آن بانك وجود ندارد.
        ///اما تراكنش هایی كه قبلا با چنین بانكی ثبت گردیده اند بدون تغییر باقی خواهند ماند..
        /// </summary>
        internal static string cBoxWithInActivesAccountBanks {
            get {
                return ResourceManager.GetString("cBoxWithInActivesAccountBanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش برنامه های غیر فعال شده توسط كاربر یا عدم نمایش آنها.
        ///در صورتی كه یك برنامه غیر فعال گردد ، امكان استفاده از آن وجود ندارد.
        ///.
        /// </summary>
        internal static string cBoxWithInActivesApplication {
            get {
                return ResourceManager.GetString("cBoxWithInActivesApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش صندوق های غیر فعال شده.
        ///در صورتی كه یك صندوق غیر فعال گردد ، امكان ثبت تراكنشی با نام این صندوق كه غیر فعال شده وجود ندارد.
        ///اما تراكنش هایی كه قبلا در چنین صندوقی ثبت گردیده اند بدون تغییر باقی خواهند ماند..
        /// </summary>
        internal static string cBoxWithInActivesCashes {
            get {
                return ResourceManager.GetString("cBoxWithInActivesCashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش طبقه بندی های غیر فعال شده.
        ///در صورتی كه یك طبقه بندی غیر فعال گردد ، امكان ثبت مدركی جدید با آن نوع ممكن نیست.
        ///اما مداركی كه قبلاً چنین نوعی داشته اند بدون تغییر باقی خواهند ماند..
        /// </summary>
        internal static string cBoxWithInActivesDocumentTypes {
            get {
                return ResourceManager.GetString("cBoxWithInActivesDocumentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش فرمول های بیمه دوم غیر فعال شده.
        ///در صورتی كه یك فرمول بیمه دوم غیر فعال گردد ،
        ///امكان ثبت مراجعه جدید با این فرمول  وجود ندارد.
        ///اما مراجعاتی كه قبلاً با چنین فرمولی ثبت گردیده اند بدون تغییر باقی خواهند ماند..
        /// </summary>
        internal static string cBoxWithInActivesIns2Formula {
            get {
                return ResourceManager.GetString("cBoxWithInActivesIns2Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش بیمه های غیر فعال شده توسط كاربر یا عدم نمایش آنها.
        ///در صورتی كه یك بیمه ی مراجعه غیر فعال گردد ، امكان ثبت مراجعه جدید با آن بیمه وجود ندارد.
        ///اما مراجعاتی كه قبلاً با چنین بیمه ای ثبت گردیده اند بدون تغییر باقی خواهند ماند..
        /// </summary>
        internal static string cBoxWithInActivesInsurances {
            get {
                return ResourceManager.GetString("cBoxWithInActivesInsurances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش شهرهای غیر فعال شده یا عدم نمایش آنها.
        ///در صورتی كه یك شهر غیر فعال گردد ، ثبت آن شهر برای بیمار جدید ممكن نیست.
        ///اما بیمارانی كه قبلا در چنین شهری ثبت گردیده اند بدون تغییر باقی خواهند ماند..
        /// </summary>
        internal static string cBoxWithInActivesPatCities {
            get {
                return ResourceManager.GetString("cBoxWithInActivesPatCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش كشورهای غیر فعال شده توسط كاربر یا عدم نمایش آنها.
        ///در صورتی كه یك كشور غیر فعال گردد ، ثبت بیماری با محل سكونتی در آن كشور ممكن نیست.
        ///اما بیمارانی كه قبلا در چنین كشوری ثبت گردیده اند بدون تغییر باقی خواهند ماند..
        /// </summary>
        internal static string cBoxWithInActivesPatCountries {
            get {
                return ResourceManager.GetString("cBoxWithInActivesPatCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش یا عدم نمایش مشاغل غیر فعال شده.
        ///در صورتی كه یك شغل غیر فعال گردد ، امكان ثبت بیماری جدید با شغل مورد نظر ممكن نیست.
        ///اما بیمارانی كه قبلا چنین شغلی داشته اند بدون تغییر باقی خواهند ماند..
        /// </summary>
        internal static string cBoxWithInActivesPatJobs {
            get {
                return ResourceManager.GetString("cBoxWithInActivesPatJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش استانهای غیر فعال شده یا عدم نمایش آنها.
        ///در صورتی كه یك استان غیر فعال گردد ، امكان ثبت بیماری با آن استام ممكن نیست.
        ///اما بیمارانی كه قبلا در چنین استانی ثبت گردیده اند بدون تغییر باقی خواهند ماند..
        /// </summary>
        internal static string cBoxWithInActivesPatStates {
            get {
                return ResourceManager.GetString("cBoxWithInActivesPatStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش تخفیف ها و هزینه های غیر فعال شده.
        ///در صورتی كه یك نوع تخفیف یا هزینه غیر فعال گردد ، امكان ثبت مورد جدیدی از آن تخفیف یا هزینه وجود ندارد.
        ///اما مواردی كه قبلاً با چنین نوعی ثبت گردیده اند بدون تغییر باقی خواهند ماند..
        /// </summary>
        internal static string cBoxWithInActivesRefCDTypes {
            get {
                return ResourceManager.GetString("cBoxWithInActivesRefCDTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش متخصصان غیر فعال شده توسط كاربر یا عدم نمایش آنها.
        ///در صورتی كه یك انجام دهنده غیر فعال گردد ، امكان ثبت خدمت برای وی ممكن نیست.
        ///اما خدماتی كه قبلاً چنین انجام دهنده ای داشته اند بدون تغییر باقی خواهند ماند..
        /// </summary>
        internal static string cBoxWithInActivesRefPerformers {
            get {
                return ResourceManager.GetString("cBoxWithInActivesRefPerformers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش پزشكان غیر فعال شده.
        ///در صورتی كه یك پزشك مراجعه غیر فعال گردد ، امكان ثبت مراجعه جدید با آن پزشك وجود ندارد.
        ///اما مراجعاتی كه قبلاً با چنین پزشكی ثبت گردیده اند بدون تغییر باقی خواهند ماند..
        /// </summary>
        internal static string cBoxWithInActivesRefPhys {
            get {
                return ResourceManager.GetString("cBoxWithInActivesRefPhys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش تخصص های غیر فعال شده.
        ///در صورتی كه یك تخصص غیر فعال گردد
        ///امكان ثبت پزشك مراجعه ای با تخصص غیر فعال وجود ممكن نیست،.
        ///اما پزشكانی كه قبلاً چنین تخصصی داشته اند بدون تغییر باقی خواهند ماند..
        /// </summary>
        internal static string cBoxWithInActivesRefPhysSpecs {
            get {
                return ResourceManager.GetString("cBoxWithInActivesRefPhysSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش وضعیت های غیر فعال شده یا عدم نمایش آنها.
        ///در صورتی كه یك وضعیت غیر فعال گردد ، امكان ثبت مراجعه بیمار با وضعیت مورد نظر ممكن نیست.
        ///اما بیمارانی كه قبلا در چنین وضعیتی ثبت شده اند بدون تغییر باقی خواهند ماند..
        /// </summary>
        internal static string cBoxWithInActivesRefStatus {
            get {
                return ResourceManager.GetString("cBoxWithInActivesRefStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش طبقه بندی های غیر فعال شده توسط كاربر یا عدم نمایش آنها.
        ///در صورتی كه یك طبقه بندی غیر فعال گردد ، امكان فیلتر كردن خدمات با آن طبقه بندی ممكن نیست..
        /// </summary>
        internal static string cBoxWithInActivesServiceCat {
            get {
                return ResourceManager.GetString("cBoxWithInActivesServiceCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش خدمات غیر فعال شده.
        ///در صورتی كه یك خدمت غیر فعال گردد ،
        ///امكان ثبت آن خدمت برای مراجعات جدید وجود ندارد.
        ///اما مراجعاتی كه قبلاً با چنین خدمتی ثبت گردیده اند بدون تغییر باقی خواهند ماند..
        /// </summary>
        internal static string cBoxWithInActivesServices {
            get {
                return ResourceManager.GetString("cBoxWithInActivesServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش گروه های غیر فعال شده.
        ///در صورتی كه یك گروه غیر فعال گردد ، امكان گزارش گیری از آن گروه ممكن نخواهد بود..
        /// </summary>
        internal static string cBoxWithInActivesServicesGroups {
            get {
                return ResourceManager.GetString("cBoxWithInActivesServicesGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش كاربران غیر فعال شده.
        ///در صورتی كه یك كاربر غیر فعال گردد ، امكان ورود به هیچ سیستمی را نخواهد داشت..
        /// </summary>
        internal static string cBoxWithInActivesUser {
            get {
                return ResourceManager.GetString("cBoxWithInActivesUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین نمایش گروه های غیر فعال شده.
        ///در صورتی كه یك گروه غیر فعال گردد ، دسترسی های تخصیص داده شده به آن گروه كاربری نادیده گرفته می شود..
        /// </summary>
        internal static string cBoxWithInActivesUserGroups {
            get {
                return ResourceManager.GetString("cBoxWithInActivesUserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش مبلغ قابل دریافت یا قابل بازپرداخت به بیمار.
        ///این مبلغ برابر مجموع &quot;پرداختنی&quot; مراجعه (ردیف اول) منهای مجموع &quot;دریافتی&quot; مراجعه (ردیف دوم) است..
        /// </summary>
        internal static string lblRecievableValue {
            get {
                return ResourceManager.GetString("lblRecievableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش روز جاری برنامه نوبت دهی.
        ///برای تغییر روز جاری بر روی این نوار كلیك نمایید..
        /// </summary>
        internal static string lblSchCurrentDate {
            get {
                return ResourceManager.GetString("lblSchCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش مجموع مبلغ پرداختنی مراجعه.
        ///این مبلغ برابر مجموع مبلغ پرداختنی &quot;خدمات&quot; فعال در مراجعه ، ضرب در تعداد خدمات ، به علاوه ی مجموع &quot;هزینه&quot; های مراجعه ، منهای مجموع &quot;تخفیف&quot; های مراجعه می باشد..
        /// </summary>
        internal static string lblTotalPayableValue {
            get {
                return ResourceManager.GetString("lblTotalPayableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش بالانس مبلغ دریافت شده مراجعه.
        ///این مبلغ برابر مجموع مبلغ &quot;دریافتی&quot; ها منهای مجموع مبلغ &quot;بازپرداخت&quot;های مراجعه میباشد.
        ///اگر عدد ارائه شده منفی باشد (كوچكتر از صفر) به معنی مجموع مبلغ بازپرداخت شده به بیمار میباشد..
        /// </summary>
        internal static string lblTotalPayedValue {
            get {
                return ResourceManager.GetString("lblTotalPayedValue", resourceCulture);
            }
        }
    }
}
