#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sepehr.DBLayerIMS.DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="PACS")]
	public partial class PACSDbLayer : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPATIENTWL(PATIENTWL instance);
    partial void UpdatePATIENTWL(PATIENTWL instance);
    partial void DeletePATIENTWL(PATIENTWL instance);
    #endregion
		
		public PACSDbLayer() : 
				base("Data Source=.\\Sqldeveloper;Initial Catalog=PACS;Integrated Security=True", mappingSource)
		{
			OnCreated();
		}
		
		public PACSDbLayer(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PACSDbLayer(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PACSDbLayer(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PACSDbLayer(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MWLWL> MWLWLs
		{
			get
			{
				return this.GetTable<MWLWL>();
			}
		}
		
		public System.Data.Linq.Table<STUDY_RI> STUDY_RIs
		{
			get
			{
				return this.GetTable<STUDY_RI>();
			}
		}
		
		public System.Data.Linq.Table<PATIENTWL> PATIENTWLs
		{
			get
			{
				return this.GetTable<PATIENTWL>();
			}
		}
	}
	
	[Table(Name="dbo.MWLWL")]
	public partial class MWLWL
	{
		
		private System.Nullable<int> _MWL_KEY;
		
		private string _TRIGGER_DTTM;
		
		private string _REPLICA_DTTM;
		
		private string _EVENT_TYPE;
		
		private string _CHARACTER_SET;
		
		private string _SCHEDULED_AETITLE;
		
		private string _SCHEDULED_DTTM;
		
		private string _SCHEDULED_MODALITY;
		
		private string _SCHEDULED_STATION;
		
		private string _SCHEDULED_LOCATION;
		
		private string _SCHEDULED_PROC_ID;
		
		private string _SCHEDULED_PROC_DESC;
		
		private string _SCHEDULED_ACTION_CODES;
		
		private string _SCHEDULED_PROC_STATUS;
		
		private string _PREMEDICATION;
		
		private string _CONTRAST_AGENT;
		
		private string _REQUESTED_PROC_ID;
		
		private string _REQUESTED_PROC_DESC;
		
		private string _REQUESTED_PROC_CODES;
		
		private string _REQUESTED_PROC_PRIORITY;
		
		private string _REQUESTED_PROC_REASON;
		
		private string _REQUESTED_PROC_COMMENTS;
		
		private string _STUDY_INSTANCE_UID;
		
		private string _PROC_PLACER_ORDER_NO;
		
		private string _PROC_FILLER_ORDER_NO;
		
		private string _ACCESSION_NO;
		
		private string _ATTEND_DOCTOR;
		
		private string _PERFORM_DOCTOR;
		
		private string _CONSULT_DOCTOR;
		
		private string _REQUEST_DOCTOR;
		
		private string _REFER_DOCTOR;
		
		private string _REQUEST_DEPARTMENT;
		
		private string _IMAGING_REQUEST_REASON;
		
		private string _IMAGING_REQUEST_COMMENTS;
		
		private string _IMAGING_REQUEST_DTTM;
		
		private string _ISR_PLACER_ORDER_NO;
		
		private string _ISR_FILLER_ORDER_NO;
		
		private string _ADMISSION_ID;
		
		private string _PATIENT_TRANSPORT;
		
		private string _PATIENT_LOCATION;
		
		private string _PATIENT_RESIDENCY;
		
		private string _PATIENT_NAME;
		
		private string _PATIENT_ID;
		
		private string _OTHER_PATIENT_NAME;
		
		private string _OTHER_PATIENT_ID;
		
		private string _PATIENT_BIRTH_DATE;
		
		private string _PATIENT_SEX;
		
		private string _PATIENT_WEIGHT;
		
		private string _PATIENT_SIZE;
		
		private string _PATIENT_STATE;
		
		private string _CONFIDENTIALITY;
		
		private string _PREGNANCY_STATUS;
		
		private string _MEDICAL_ALERTS;
		
		private string _CONTRAST_ALLERGIES;
		
		private string _SPECIAL_NEEDS;
		
		private string _SPECIALTY;
		
		private string _DIAGNOSIS;
		
		private string _ADMIT_DTTM;
		
		private string _REGISTER_DTTM;
		
		public MWLWL()
		{
		}
		
		[Column(Storage="_MWL_KEY", DbType="Int")]
		public System.Nullable<int> MWL_KEY
		{
			get
			{
				return this._MWL_KEY;
			}
			set
			{
				if ((this._MWL_KEY != value))
				{
					this._MWL_KEY = value;
				}
			}
		}
		
		[Column(Storage="_TRIGGER_DTTM", DbType="NVarChar(255)")]
		public string TRIGGER_DTTM
		{
			get
			{
				return this._TRIGGER_DTTM;
			}
			set
			{
				if ((this._TRIGGER_DTTM != value))
				{
					this._TRIGGER_DTTM = value;
				}
			}
		}
		
		[Column(Storage="_REPLICA_DTTM", DbType="NVarChar(255)")]
		public string REPLICA_DTTM
		{
			get
			{
				return this._REPLICA_DTTM;
			}
			set
			{
				if ((this._REPLICA_DTTM != value))
				{
					this._REPLICA_DTTM = value;
				}
			}
		}
		
		[Column(Storage="_EVENT_TYPE", DbType="NVarChar(255)")]
		public string EVENT_TYPE
		{
			get
			{
				return this._EVENT_TYPE;
			}
			set
			{
				if ((this._EVENT_TYPE != value))
				{
					this._EVENT_TYPE = value;
				}
			}
		}
		
		[Column(Storage="_CHARACTER_SET", DbType="NVarChar(255)")]
		public string CHARACTER_SET
		{
			get
			{
				return this._CHARACTER_SET;
			}
			set
			{
				if ((this._CHARACTER_SET != value))
				{
					this._CHARACTER_SET = value;
				}
			}
		}
		
		[Column(Storage="_SCHEDULED_AETITLE", DbType="NVarChar(255)")]
		public string SCHEDULED_AETITLE
		{
			get
			{
				return this._SCHEDULED_AETITLE;
			}
			set
			{
				if ((this._SCHEDULED_AETITLE != value))
				{
					this._SCHEDULED_AETITLE = value;
				}
			}
		}
		
		[Column(Storage="_SCHEDULED_DTTM", DbType="NVarChar(255)")]
		public string SCHEDULED_DTTM
		{
			get
			{
				return this._SCHEDULED_DTTM;
			}
			set
			{
				if ((this._SCHEDULED_DTTM != value))
				{
					this._SCHEDULED_DTTM = value;
				}
			}
		}
		
		[Column(Storage="_SCHEDULED_MODALITY", DbType="NVarChar(255)")]
		public string SCHEDULED_MODALITY
		{
			get
			{
				return this._SCHEDULED_MODALITY;
			}
			set
			{
				if ((this._SCHEDULED_MODALITY != value))
				{
					this._SCHEDULED_MODALITY = value;
				}
			}
		}
		
		[Column(Storage="_SCHEDULED_STATION", DbType="NVarChar(255)")]
		public string SCHEDULED_STATION
		{
			get
			{
				return this._SCHEDULED_STATION;
			}
			set
			{
				if ((this._SCHEDULED_STATION != value))
				{
					this._SCHEDULED_STATION = value;
				}
			}
		}
		
		[Column(Storage="_SCHEDULED_LOCATION", DbType="NVarChar(255)")]
		public string SCHEDULED_LOCATION
		{
			get
			{
				return this._SCHEDULED_LOCATION;
			}
			set
			{
				if ((this._SCHEDULED_LOCATION != value))
				{
					this._SCHEDULED_LOCATION = value;
				}
			}
		}
		
		[Column(Storage="_SCHEDULED_PROC_ID", DbType="NVarChar(255)")]
		public string SCHEDULED_PROC_ID
		{
			get
			{
				return this._SCHEDULED_PROC_ID;
			}
			set
			{
				if ((this._SCHEDULED_PROC_ID != value))
				{
					this._SCHEDULED_PROC_ID = value;
				}
			}
		}
		
		[Column(Storage="_SCHEDULED_PROC_DESC", DbType="NVarChar(255)")]
		public string SCHEDULED_PROC_DESC
		{
			get
			{
				return this._SCHEDULED_PROC_DESC;
			}
			set
			{
				if ((this._SCHEDULED_PROC_DESC != value))
				{
					this._SCHEDULED_PROC_DESC = value;
				}
			}
		}
		
		[Column(Storage="_SCHEDULED_ACTION_CODES", DbType="NVarChar(255)")]
		public string SCHEDULED_ACTION_CODES
		{
			get
			{
				return this._SCHEDULED_ACTION_CODES;
			}
			set
			{
				if ((this._SCHEDULED_ACTION_CODES != value))
				{
					this._SCHEDULED_ACTION_CODES = value;
				}
			}
		}
		
		[Column(Storage="_SCHEDULED_PROC_STATUS", DbType="NVarChar(255)")]
		public string SCHEDULED_PROC_STATUS
		{
			get
			{
				return this._SCHEDULED_PROC_STATUS;
			}
			set
			{
				if ((this._SCHEDULED_PROC_STATUS != value))
				{
					this._SCHEDULED_PROC_STATUS = value;
				}
			}
		}
		
		[Column(Storage="_PREMEDICATION", DbType="NVarChar(255)")]
		public string PREMEDICATION
		{
			get
			{
				return this._PREMEDICATION;
			}
			set
			{
				if ((this._PREMEDICATION != value))
				{
					this._PREMEDICATION = value;
				}
			}
		}
		
		[Column(Storage="_CONTRAST_AGENT", DbType="NVarChar(255)")]
		public string CONTRAST_AGENT
		{
			get
			{
				return this._CONTRAST_AGENT;
			}
			set
			{
				if ((this._CONTRAST_AGENT != value))
				{
					this._CONTRAST_AGENT = value;
				}
			}
		}
		
		[Column(Storage="_REQUESTED_PROC_ID", DbType="NVarChar(255)")]
		public string REQUESTED_PROC_ID
		{
			get
			{
				return this._REQUESTED_PROC_ID;
			}
			set
			{
				if ((this._REQUESTED_PROC_ID != value))
				{
					this._REQUESTED_PROC_ID = value;
				}
			}
		}
		
		[Column(Storage="_REQUESTED_PROC_DESC", DbType="NVarChar(255)")]
		public string REQUESTED_PROC_DESC
		{
			get
			{
				return this._REQUESTED_PROC_DESC;
			}
			set
			{
				if ((this._REQUESTED_PROC_DESC != value))
				{
					this._REQUESTED_PROC_DESC = value;
				}
			}
		}
		
		[Column(Storage="_REQUESTED_PROC_CODES", DbType="NVarChar(255)")]
		public string REQUESTED_PROC_CODES
		{
			get
			{
				return this._REQUESTED_PROC_CODES;
			}
			set
			{
				if ((this._REQUESTED_PROC_CODES != value))
				{
					this._REQUESTED_PROC_CODES = value;
				}
			}
		}
		
		[Column(Storage="_REQUESTED_PROC_PRIORITY", DbType="NVarChar(255)")]
		public string REQUESTED_PROC_PRIORITY
		{
			get
			{
				return this._REQUESTED_PROC_PRIORITY;
			}
			set
			{
				if ((this._REQUESTED_PROC_PRIORITY != value))
				{
					this._REQUESTED_PROC_PRIORITY = value;
				}
			}
		}
		
		[Column(Storage="_REQUESTED_PROC_REASON", DbType="NVarChar(255)")]
		public string REQUESTED_PROC_REASON
		{
			get
			{
				return this._REQUESTED_PROC_REASON;
			}
			set
			{
				if ((this._REQUESTED_PROC_REASON != value))
				{
					this._REQUESTED_PROC_REASON = value;
				}
			}
		}
		
		[Column(Storage="_REQUESTED_PROC_COMMENTS", DbType="NVarChar(255)")]
		public string REQUESTED_PROC_COMMENTS
		{
			get
			{
				return this._REQUESTED_PROC_COMMENTS;
			}
			set
			{
				if ((this._REQUESTED_PROC_COMMENTS != value))
				{
					this._REQUESTED_PROC_COMMENTS = value;
				}
			}
		}
		
		[Column(Storage="_STUDY_INSTANCE_UID", DbType="NVarChar(255)")]
		public string STUDY_INSTANCE_UID
		{
			get
			{
				return this._STUDY_INSTANCE_UID;
			}
			set
			{
				if ((this._STUDY_INSTANCE_UID != value))
				{
					this._STUDY_INSTANCE_UID = value;
				}
			}
		}
		
		[Column(Storage="_PROC_PLACER_ORDER_NO", DbType="NVarChar(255)")]
		public string PROC_PLACER_ORDER_NO
		{
			get
			{
				return this._PROC_PLACER_ORDER_NO;
			}
			set
			{
				if ((this._PROC_PLACER_ORDER_NO != value))
				{
					this._PROC_PLACER_ORDER_NO = value;
				}
			}
		}
		
		[Column(Storage="_PROC_FILLER_ORDER_NO", DbType="NVarChar(255)")]
		public string PROC_FILLER_ORDER_NO
		{
			get
			{
				return this._PROC_FILLER_ORDER_NO;
			}
			set
			{
				if ((this._PROC_FILLER_ORDER_NO != value))
				{
					this._PROC_FILLER_ORDER_NO = value;
				}
			}
		}
		
		[Column(Storage="_ACCESSION_NO", DbType="NVarChar(255)")]
		public string ACCESSION_NO
		{
			get
			{
				return this._ACCESSION_NO;
			}
			set
			{
				if ((this._ACCESSION_NO != value))
				{
					this._ACCESSION_NO = value;
				}
			}
		}
		
		[Column(Storage="_ATTEND_DOCTOR", DbType="NVarChar(255)")]
		public string ATTEND_DOCTOR
		{
			get
			{
				return this._ATTEND_DOCTOR;
			}
			set
			{
				if ((this._ATTEND_DOCTOR != value))
				{
					this._ATTEND_DOCTOR = value;
				}
			}
		}
		
		[Column(Storage="_PERFORM_DOCTOR", DbType="NVarChar(255)")]
		public string PERFORM_DOCTOR
		{
			get
			{
				return this._PERFORM_DOCTOR;
			}
			set
			{
				if ((this._PERFORM_DOCTOR != value))
				{
					this._PERFORM_DOCTOR = value;
				}
			}
		}
		
		[Column(Storage="_CONSULT_DOCTOR", DbType="NVarChar(255)")]
		public string CONSULT_DOCTOR
		{
			get
			{
				return this._CONSULT_DOCTOR;
			}
			set
			{
				if ((this._CONSULT_DOCTOR != value))
				{
					this._CONSULT_DOCTOR = value;
				}
			}
		}
		
		[Column(Storage="_REQUEST_DOCTOR", DbType="NVarChar(255)")]
		public string REQUEST_DOCTOR
		{
			get
			{
				return this._REQUEST_DOCTOR;
			}
			set
			{
				if ((this._REQUEST_DOCTOR != value))
				{
					this._REQUEST_DOCTOR = value;
				}
			}
		}
		
		[Column(Storage="_REFER_DOCTOR", DbType="NVarChar(255)")]
		public string REFER_DOCTOR
		{
			get
			{
				return this._REFER_DOCTOR;
			}
			set
			{
				if ((this._REFER_DOCTOR != value))
				{
					this._REFER_DOCTOR = value;
				}
			}
		}
		
		[Column(Storage="_REQUEST_DEPARTMENT", DbType="NVarChar(255)")]
		public string REQUEST_DEPARTMENT
		{
			get
			{
				return this._REQUEST_DEPARTMENT;
			}
			set
			{
				if ((this._REQUEST_DEPARTMENT != value))
				{
					this._REQUEST_DEPARTMENT = value;
				}
			}
		}
		
		[Column(Storage="_IMAGING_REQUEST_REASON", DbType="NVarChar(255)")]
		public string IMAGING_REQUEST_REASON
		{
			get
			{
				return this._IMAGING_REQUEST_REASON;
			}
			set
			{
				if ((this._IMAGING_REQUEST_REASON != value))
				{
					this._IMAGING_REQUEST_REASON = value;
				}
			}
		}
		
		[Column(Storage="_IMAGING_REQUEST_COMMENTS", DbType="NVarChar(255)")]
		public string IMAGING_REQUEST_COMMENTS
		{
			get
			{
				return this._IMAGING_REQUEST_COMMENTS;
			}
			set
			{
				if ((this._IMAGING_REQUEST_COMMENTS != value))
				{
					this._IMAGING_REQUEST_COMMENTS = value;
				}
			}
		}
		
		[Column(Storage="_IMAGING_REQUEST_DTTM", DbType="NVarChar(255)")]
		public string IMAGING_REQUEST_DTTM
		{
			get
			{
				return this._IMAGING_REQUEST_DTTM;
			}
			set
			{
				if ((this._IMAGING_REQUEST_DTTM != value))
				{
					this._IMAGING_REQUEST_DTTM = value;
				}
			}
		}
		
		[Column(Storage="_ISR_PLACER_ORDER_NO", DbType="NVarChar(255)")]
		public string ISR_PLACER_ORDER_NO
		{
			get
			{
				return this._ISR_PLACER_ORDER_NO;
			}
			set
			{
				if ((this._ISR_PLACER_ORDER_NO != value))
				{
					this._ISR_PLACER_ORDER_NO = value;
				}
			}
		}
		
		[Column(Storage="_ISR_FILLER_ORDER_NO", DbType="NVarChar(255)")]
		public string ISR_FILLER_ORDER_NO
		{
			get
			{
				return this._ISR_FILLER_ORDER_NO;
			}
			set
			{
				if ((this._ISR_FILLER_ORDER_NO != value))
				{
					this._ISR_FILLER_ORDER_NO = value;
				}
			}
		}
		
		[Column(Storage="_ADMISSION_ID", DbType="NVarChar(255)")]
		public string ADMISSION_ID
		{
			get
			{
				return this._ADMISSION_ID;
			}
			set
			{
				if ((this._ADMISSION_ID != value))
				{
					this._ADMISSION_ID = value;
				}
			}
		}
		
		[Column(Storage="_PATIENT_TRANSPORT", DbType="NVarChar(255)")]
		public string PATIENT_TRANSPORT
		{
			get
			{
				return this._PATIENT_TRANSPORT;
			}
			set
			{
				if ((this._PATIENT_TRANSPORT != value))
				{
					this._PATIENT_TRANSPORT = value;
				}
			}
		}
		
		[Column(Storage="_PATIENT_LOCATION", DbType="NVarChar(255)")]
		public string PATIENT_LOCATION
		{
			get
			{
				return this._PATIENT_LOCATION;
			}
			set
			{
				if ((this._PATIENT_LOCATION != value))
				{
					this._PATIENT_LOCATION = value;
				}
			}
		}
		
		[Column(Storage="_PATIENT_RESIDENCY", DbType="NVarChar(255)")]
		public string PATIENT_RESIDENCY
		{
			get
			{
				return this._PATIENT_RESIDENCY;
			}
			set
			{
				if ((this._PATIENT_RESIDENCY != value))
				{
					this._PATIENT_RESIDENCY = value;
				}
			}
		}
		
		[Column(Storage="_PATIENT_NAME", DbType="NVarChar(255)")]
		public string PATIENT_NAME
		{
			get
			{
				return this._PATIENT_NAME;
			}
			set
			{
				if ((this._PATIENT_NAME != value))
				{
					this._PATIENT_NAME = value;
				}
			}
		}
		
		[Column(Storage="_PATIENT_ID", DbType="NVarChar(255)")]
		public string PATIENT_ID
		{
			get
			{
				return this._PATIENT_ID;
			}
			set
			{
				if ((this._PATIENT_ID != value))
				{
					this._PATIENT_ID = value;
				}
			}
		}
		
		[Column(Storage="_OTHER_PATIENT_NAME", DbType="NVarChar(255)")]
		public string OTHER_PATIENT_NAME
		{
			get
			{
				return this._OTHER_PATIENT_NAME;
			}
			set
			{
				if ((this._OTHER_PATIENT_NAME != value))
				{
					this._OTHER_PATIENT_NAME = value;
				}
			}
		}
		
		[Column(Storage="_OTHER_PATIENT_ID", DbType="NVarChar(255)")]
		public string OTHER_PATIENT_ID
		{
			get
			{
				return this._OTHER_PATIENT_ID;
			}
			set
			{
				if ((this._OTHER_PATIENT_ID != value))
				{
					this._OTHER_PATIENT_ID = value;
				}
			}
		}
		
		[Column(Storage="_PATIENT_BIRTH_DATE", DbType="NVarChar(255)")]
		public string PATIENT_BIRTH_DATE
		{
			get
			{
				return this._PATIENT_BIRTH_DATE;
			}
			set
			{
				if ((this._PATIENT_BIRTH_DATE != value))
				{
					this._PATIENT_BIRTH_DATE = value;
				}
			}
		}
		
		[Column(Storage="_PATIENT_SEX", DbType="NVarChar(255)")]
		public string PATIENT_SEX
		{
			get
			{
				return this._PATIENT_SEX;
			}
			set
			{
				if ((this._PATIENT_SEX != value))
				{
					this._PATIENT_SEX = value;
				}
			}
		}
		
		[Column(Storage="_PATIENT_WEIGHT", DbType="NVarChar(255)")]
		public string PATIENT_WEIGHT
		{
			get
			{
				return this._PATIENT_WEIGHT;
			}
			set
			{
				if ((this._PATIENT_WEIGHT != value))
				{
					this._PATIENT_WEIGHT = value;
				}
			}
		}
		
		[Column(Storage="_PATIENT_SIZE", DbType="NVarChar(255)")]
		public string PATIENT_SIZE
		{
			get
			{
				return this._PATIENT_SIZE;
			}
			set
			{
				if ((this._PATIENT_SIZE != value))
				{
					this._PATIENT_SIZE = value;
				}
			}
		}
		
		[Column(Storage="_PATIENT_STATE", DbType="NVarChar(255)")]
		public string PATIENT_STATE
		{
			get
			{
				return this._PATIENT_STATE;
			}
			set
			{
				if ((this._PATIENT_STATE != value))
				{
					this._PATIENT_STATE = value;
				}
			}
		}
		
		[Column(Storage="_CONFIDENTIALITY", DbType="NVarChar(255)")]
		public string CONFIDENTIALITY
		{
			get
			{
				return this._CONFIDENTIALITY;
			}
			set
			{
				if ((this._CONFIDENTIALITY != value))
				{
					this._CONFIDENTIALITY = value;
				}
			}
		}
		
		[Column(Storage="_PREGNANCY_STATUS", DbType="NVarChar(255)")]
		public string PREGNANCY_STATUS
		{
			get
			{
				return this._PREGNANCY_STATUS;
			}
			set
			{
				if ((this._PREGNANCY_STATUS != value))
				{
					this._PREGNANCY_STATUS = value;
				}
			}
		}
		
		[Column(Storage="_MEDICAL_ALERTS", DbType="NVarChar(255)")]
		public string MEDICAL_ALERTS
		{
			get
			{
				return this._MEDICAL_ALERTS;
			}
			set
			{
				if ((this._MEDICAL_ALERTS != value))
				{
					this._MEDICAL_ALERTS = value;
				}
			}
		}
		
		[Column(Storage="_CONTRAST_ALLERGIES", DbType="NVarChar(255)")]
		public string CONTRAST_ALLERGIES
		{
			get
			{
				return this._CONTRAST_ALLERGIES;
			}
			set
			{
				if ((this._CONTRAST_ALLERGIES != value))
				{
					this._CONTRAST_ALLERGIES = value;
				}
			}
		}
		
		[Column(Storage="_SPECIAL_NEEDS", DbType="NVarChar(255)")]
		public string SPECIAL_NEEDS
		{
			get
			{
				return this._SPECIAL_NEEDS;
			}
			set
			{
				if ((this._SPECIAL_NEEDS != value))
				{
					this._SPECIAL_NEEDS = value;
				}
			}
		}
		
		[Column(Storage="_SPECIALTY", DbType="NVarChar(255)")]
		public string SPECIALTY
		{
			get
			{
				return this._SPECIALTY;
			}
			set
			{
				if ((this._SPECIALTY != value))
				{
					this._SPECIALTY = value;
				}
			}
		}
		
		[Column(Storage="_DIAGNOSIS", DbType="NVarChar(255)")]
		public string DIAGNOSIS
		{
			get
			{
				return this._DIAGNOSIS;
			}
			set
			{
				if ((this._DIAGNOSIS != value))
				{
					this._DIAGNOSIS = value;
				}
			}
		}
		
		[Column(Storage="_ADMIT_DTTM", DbType="NVarChar(255)")]
		public string ADMIT_DTTM
		{
			get
			{
				return this._ADMIT_DTTM;
			}
			set
			{
				if ((this._ADMIT_DTTM != value))
				{
					this._ADMIT_DTTM = value;
				}
			}
		}
		
		[Column(Storage="_REGISTER_DTTM", DbType="NVarChar(255)")]
		public string REGISTER_DTTM
		{
			get
			{
				return this._REGISTER_DTTM;
			}
			set
			{
				if ((this._REGISTER_DTTM != value))
				{
					this._REGISTER_DTTM = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.STUDY_RIS")]
	public partial class STUDY_RI
	{
		
		private string _input_date;
		
		private string _Study_Key;
		
		private string _Patient_Id;
		
		private string _accession_no;
		
		private string _Study_Stat;
		
		private string _Study_Instance_UID;
		
		private string _Study_Dttm;
		
		private string _Request_Code;
		
		private string _Request_Name;
		
		private string _Perform_Modality;
		
		private string _Perform_Station;
		
		private string _Source_AETitle;
		
		private string _Scheduled_Location;
		
		private string _Perform_Department;
		
		private string _Scheduled_Dttm;
		
		private string _Patient_Location;
		
		private string _Request_Dttm;
		
		private string _admission_id;
		
		private string _request_doctor;
		
		public STUDY_RI()
		{
		}
		
		[Column(Storage="_input_date", DbType="NVarChar(255)")]
		public string input_date
		{
			get
			{
				return this._input_date;
			}
			set
			{
				if ((this._input_date != value))
				{
					this._input_date = value;
				}
			}
		}
		
		[Column(Storage="_Study_Key", DbType="NVarChar(255)")]
		public string Study_Key
		{
			get
			{
				return this._Study_Key;
			}
			set
			{
				if ((this._Study_Key != value))
				{
					this._Study_Key = value;
				}
			}
		}
		
		[Column(Storage="_Patient_Id", DbType="NVarChar(255)")]
		public string Patient_Id
		{
			get
			{
				return this._Patient_Id;
			}
			set
			{
				if ((this._Patient_Id != value))
				{
					this._Patient_Id = value;
				}
			}
		}
		
		[Column(Storage="_accession_no", DbType="NVarChar(255)")]
		public string accession_no
		{
			get
			{
				return this._accession_no;
			}
			set
			{
				if ((this._accession_no != value))
				{
					this._accession_no = value;
				}
			}
		}
		
		[Column(Storage="_Study_Stat", DbType="NVarChar(255)")]
		public string Study_Stat
		{
			get
			{
				return this._Study_Stat;
			}
			set
			{
				if ((this._Study_Stat != value))
				{
					this._Study_Stat = value;
				}
			}
		}
		
		[Column(Storage="_Study_Instance_UID", DbType="NVarChar(255)")]
		public string Study_Instance_UID
		{
			get
			{
				return this._Study_Instance_UID;
			}
			set
			{
				if ((this._Study_Instance_UID != value))
				{
					this._Study_Instance_UID = value;
				}
			}
		}
		
		[Column(Storage="_Study_Dttm", DbType="NVarChar(255)")]
		public string Study_Dttm
		{
			get
			{
				return this._Study_Dttm;
			}
			set
			{
				if ((this._Study_Dttm != value))
				{
					this._Study_Dttm = value;
				}
			}
		}
		
		[Column(Storage="_Request_Code", DbType="NVarChar(255)")]
		public string Request_Code
		{
			get
			{
				return this._Request_Code;
			}
			set
			{
				if ((this._Request_Code != value))
				{
					this._Request_Code = value;
				}
			}
		}
		
		[Column(Storage="_Request_Name", DbType="NVarChar(255)")]
		public string Request_Name
		{
			get
			{
				return this._Request_Name;
			}
			set
			{
				if ((this._Request_Name != value))
				{
					this._Request_Name = value;
				}
			}
		}
		
		[Column(Storage="_Perform_Modality", DbType="NVarChar(255)")]
		public string Perform_Modality
		{
			get
			{
				return this._Perform_Modality;
			}
			set
			{
				if ((this._Perform_Modality != value))
				{
					this._Perform_Modality = value;
				}
			}
		}
		
		[Column(Storage="_Perform_Station", DbType="NVarChar(255)")]
		public string Perform_Station
		{
			get
			{
				return this._Perform_Station;
			}
			set
			{
				if ((this._Perform_Station != value))
				{
					this._Perform_Station = value;
				}
			}
		}
		
		[Column(Storage="_Source_AETitle", DbType="NVarChar(255)")]
		public string Source_AETitle
		{
			get
			{
				return this._Source_AETitle;
			}
			set
			{
				if ((this._Source_AETitle != value))
				{
					this._Source_AETitle = value;
				}
			}
		}
		
		[Column(Storage="_Scheduled_Location", DbType="NVarChar(255)")]
		public string Scheduled_Location
		{
			get
			{
				return this._Scheduled_Location;
			}
			set
			{
				if ((this._Scheduled_Location != value))
				{
					this._Scheduled_Location = value;
				}
			}
		}
		
		[Column(Storage="_Perform_Department", DbType="NVarChar(255)")]
		public string Perform_Department
		{
			get
			{
				return this._Perform_Department;
			}
			set
			{
				if ((this._Perform_Department != value))
				{
					this._Perform_Department = value;
				}
			}
		}
		
		[Column(Storage="_Scheduled_Dttm", DbType="NVarChar(255)")]
		public string Scheduled_Dttm
		{
			get
			{
				return this._Scheduled_Dttm;
			}
			set
			{
				if ((this._Scheduled_Dttm != value))
				{
					this._Scheduled_Dttm = value;
				}
			}
		}
		
		[Column(Storage="_Patient_Location", DbType="NVarChar(255)")]
		public string Patient_Location
		{
			get
			{
				return this._Patient_Location;
			}
			set
			{
				if ((this._Patient_Location != value))
				{
					this._Patient_Location = value;
				}
			}
		}
		
		[Column(Storage="_Request_Dttm", DbType="NVarChar(255)")]
		public string Request_Dttm
		{
			get
			{
				return this._Request_Dttm;
			}
			set
			{
				if ((this._Request_Dttm != value))
				{
					this._Request_Dttm = value;
				}
			}
		}
		
		[Column(Storage="_admission_id", DbType="NVarChar(255)")]
		public string admission_id
		{
			get
			{
				return this._admission_id;
			}
			set
			{
				if ((this._admission_id != value))
				{
					this._admission_id = value;
				}
			}
		}
		
		[Column(Storage="_request_doctor", DbType="NVarChar(255)")]
		public string request_doctor
		{
			get
			{
				return this._request_doctor;
			}
			set
			{
				if ((this._request_doctor != value))
				{
					this._request_doctor = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.PATIENTWL")]
	public partial class PATIENTWL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _PATIENTWL_KEY;
		
		private string _TRIGGER_DTTM;
		
		private string _REPLICA_DTTM;
		
		private string _EVENT_TYPE;
		
		private string _PATIENT_ID;
		
		private string _PATIENT_NAME;
		
		private string _ENGLISH_NAME;
		
		private string _PATIENT_SSN;
		
		private string _PATIENT_BIRTH_DTTM;
		
		private string _PATIENT_SEX;
		
		private string _PATIENT_WEIGHT;
		
		private string _PATIENT_SIZE;
		
		private string _ETHNIC_GROUP;
		
		private string _TEL_NO;
		
		private string _FAX_NO;
		
		private string _ZIPCODE;
		
		private string _ADDRESS;
		
		private string _EMAIL;
		
		private string _BLOOD_TYPE;
		
		private string _PREGNANCY_STATUS;
		
		private string _CURRENT_LOCATION;
		
		private string _CURRENT_RESIDENCY;
		
		private string _CURRENT_DEPARTMENT;
		
		private string _CURRENT_DOCTOR_ID;
		
		private string _CURRENT_DOCTOR_NAME;
		
		private string _ADMIT_DTTM;
		
		private string _DISCHARGE_DTTM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPATIENTWL_KEYChanging(System.Nullable<int> value);
    partial void OnPATIENTWL_KEYChanged();
    partial void OnTRIGGER_DTTMChanging(string value);
    partial void OnTRIGGER_DTTMChanged();
    partial void OnREPLICA_DTTMChanging(string value);
    partial void OnREPLICA_DTTMChanged();
    partial void OnEVENT_TYPEChanging(string value);
    partial void OnEVENT_TYPEChanged();
    partial void OnPATIENT_IDChanging(string value);
    partial void OnPATIENT_IDChanged();
    partial void OnPATIENT_NAMEChanging(string value);
    partial void OnPATIENT_NAMEChanged();
    partial void OnENGLISH_NAMEChanging(string value);
    partial void OnENGLISH_NAMEChanged();
    partial void OnPATIENT_SSNChanging(string value);
    partial void OnPATIENT_SSNChanged();
    partial void OnPATIENT_BIRTH_DTTMChanging(string value);
    partial void OnPATIENT_BIRTH_DTTMChanged();
    partial void OnPATIENT_SEXChanging(string value);
    partial void OnPATIENT_SEXChanged();
    partial void OnPATIENT_WEIGHTChanging(string value);
    partial void OnPATIENT_WEIGHTChanged();
    partial void OnPATIENT_SIZEChanging(string value);
    partial void OnPATIENT_SIZEChanged();
    partial void OnETHNIC_GROUPChanging(string value);
    partial void OnETHNIC_GROUPChanged();
    partial void OnTEL_NOChanging(string value);
    partial void OnTEL_NOChanged();
    partial void OnFAX_NOChanging(string value);
    partial void OnFAX_NOChanged();
    partial void OnZIPCODEChanging(string value);
    partial void OnZIPCODEChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnBLOOD_TYPEChanging(string value);
    partial void OnBLOOD_TYPEChanged();
    partial void OnPREGNANCY_STATUSChanging(string value);
    partial void OnPREGNANCY_STATUSChanged();
    partial void OnCURRENT_LOCATIONChanging(string value);
    partial void OnCURRENT_LOCATIONChanged();
    partial void OnCURRENT_RESIDENCYChanging(string value);
    partial void OnCURRENT_RESIDENCYChanged();
    partial void OnCURRENT_DEPARTMENTChanging(string value);
    partial void OnCURRENT_DEPARTMENTChanged();
    partial void OnCURRENT_DOCTOR_IDChanging(string value);
    partial void OnCURRENT_DOCTOR_IDChanged();
    partial void OnCURRENT_DOCTOR_NAMEChanging(string value);
    partial void OnCURRENT_DOCTOR_NAMEChanged();
    partial void OnADMIT_DTTMChanging(string value);
    partial void OnADMIT_DTTMChanged();
    partial void OnDISCHARGE_DTTMChanging(string value);
    partial void OnDISCHARGE_DTTMChanged();
    #endregion
		
		public PATIENTWL()
		{
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_PATIENTWL_KEY", DbType="Int")]
		public System.Nullable<int> PATIENTWL_KEY
		{
			get
			{
				return this._PATIENTWL_KEY;
			}
			set
			{
				if ((this._PATIENTWL_KEY != value))
				{
					this.OnPATIENTWL_KEYChanging(value);
					this.SendPropertyChanging();
					this._PATIENTWL_KEY = value;
					this.SendPropertyChanged("PATIENTWL_KEY");
					this.OnPATIENTWL_KEYChanged();
				}
			}
		}
		
		[Column(Storage="_TRIGGER_DTTM", DbType="NVarChar(255)")]
		public string TRIGGER_DTTM
		{
			get
			{
				return this._TRIGGER_DTTM;
			}
			set
			{
				if ((this._TRIGGER_DTTM != value))
				{
					this.OnTRIGGER_DTTMChanging(value);
					this.SendPropertyChanging();
					this._TRIGGER_DTTM = value;
					this.SendPropertyChanged("TRIGGER_DTTM");
					this.OnTRIGGER_DTTMChanged();
				}
			}
		}
		
		[Column(Storage="_REPLICA_DTTM", DbType="NVarChar(255)")]
		public string REPLICA_DTTM
		{
			get
			{
				return this._REPLICA_DTTM;
			}
			set
			{
				if ((this._REPLICA_DTTM != value))
				{
					this.OnREPLICA_DTTMChanging(value);
					this.SendPropertyChanging();
					this._REPLICA_DTTM = value;
					this.SendPropertyChanged("REPLICA_DTTM");
					this.OnREPLICA_DTTMChanged();
				}
			}
		}
		
		[Column(Storage="_EVENT_TYPE", DbType="NVarChar(255)")]
		public string EVENT_TYPE
		{
			get
			{
				return this._EVENT_TYPE;
			}
			set
			{
				if ((this._EVENT_TYPE != value))
				{
					this.OnEVENT_TYPEChanging(value);
					this.SendPropertyChanging();
					this._EVENT_TYPE = value;
					this.SendPropertyChanged("EVENT_TYPE");
					this.OnEVENT_TYPEChanged();
				}
			}
		}
		
		[Column(Storage="_PATIENT_ID", DbType="NVarChar(255)")]
		public string PATIENT_ID
		{
			get
			{
				return this._PATIENT_ID;
			}
			set
			{
				if ((this._PATIENT_ID != value))
				{
					this.OnPATIENT_IDChanging(value);
					this.SendPropertyChanging();
					this._PATIENT_ID = value;
					this.SendPropertyChanged("PATIENT_ID");
					this.OnPATIENT_IDChanged();
				}
			}
		}
		
		[Column(Storage="_PATIENT_NAME", DbType="NVarChar(255)")]
		public string PATIENT_NAME
		{
			get
			{
				return this._PATIENT_NAME;
			}
			set
			{
				if ((this._PATIENT_NAME != value))
				{
					this.OnPATIENT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PATIENT_NAME = value;
					this.SendPropertyChanged("PATIENT_NAME");
					this.OnPATIENT_NAMEChanged();
				}
			}
		}
		
		[Column(Storage="_ENGLISH_NAME", DbType="NVarChar(255)")]
		public string ENGLISH_NAME
		{
			get
			{
				return this._ENGLISH_NAME;
			}
			set
			{
				if ((this._ENGLISH_NAME != value))
				{
					this.OnENGLISH_NAMEChanging(value);
					this.SendPropertyChanging();
					this._ENGLISH_NAME = value;
					this.SendPropertyChanged("ENGLISH_NAME");
					this.OnENGLISH_NAMEChanged();
				}
			}
		}
		
		[Column(Storage="_PATIENT_SSN", DbType="NVarChar(255)")]
		public string PATIENT_SSN
		{
			get
			{
				return this._PATIENT_SSN;
			}
			set
			{
				if ((this._PATIENT_SSN != value))
				{
					this.OnPATIENT_SSNChanging(value);
					this.SendPropertyChanging();
					this._PATIENT_SSN = value;
					this.SendPropertyChanged("PATIENT_SSN");
					this.OnPATIENT_SSNChanged();
				}
			}
		}
		
		[Column(Storage="_PATIENT_BIRTH_DTTM", DbType="NVarChar(255)")]
		public string PATIENT_BIRTH_DTTM
		{
			get
			{
				return this._PATIENT_BIRTH_DTTM;
			}
			set
			{
				if ((this._PATIENT_BIRTH_DTTM != value))
				{
					this.OnPATIENT_BIRTH_DTTMChanging(value);
					this.SendPropertyChanging();
					this._PATIENT_BIRTH_DTTM = value;
					this.SendPropertyChanged("PATIENT_BIRTH_DTTM");
					this.OnPATIENT_BIRTH_DTTMChanged();
				}
			}
		}
		
		[Column(Storage="_PATIENT_SEX", DbType="NVarChar(255)")]
		public string PATIENT_SEX
		{
			get
			{
				return this._PATIENT_SEX;
			}
			set
			{
				if ((this._PATIENT_SEX != value))
				{
					this.OnPATIENT_SEXChanging(value);
					this.SendPropertyChanging();
					this._PATIENT_SEX = value;
					this.SendPropertyChanged("PATIENT_SEX");
					this.OnPATIENT_SEXChanged();
				}
			}
		}
		
		[Column(Storage="_PATIENT_WEIGHT", DbType="NVarChar(255)")]
		public string PATIENT_WEIGHT
		{
			get
			{
				return this._PATIENT_WEIGHT;
			}
			set
			{
				if ((this._PATIENT_WEIGHT != value))
				{
					this.OnPATIENT_WEIGHTChanging(value);
					this.SendPropertyChanging();
					this._PATIENT_WEIGHT = value;
					this.SendPropertyChanged("PATIENT_WEIGHT");
					this.OnPATIENT_WEIGHTChanged();
				}
			}
		}
		
		[Column(Storage="_PATIENT_SIZE", DbType="NVarChar(255)")]
		public string PATIENT_SIZE
		{
			get
			{
				return this._PATIENT_SIZE;
			}
			set
			{
				if ((this._PATIENT_SIZE != value))
				{
					this.OnPATIENT_SIZEChanging(value);
					this.SendPropertyChanging();
					this._PATIENT_SIZE = value;
					this.SendPropertyChanged("PATIENT_SIZE");
					this.OnPATIENT_SIZEChanged();
				}
			}
		}
		
		[Column(Storage="_ETHNIC_GROUP", DbType="NVarChar(255)")]
		public string ETHNIC_GROUP
		{
			get
			{
				return this._ETHNIC_GROUP;
			}
			set
			{
				if ((this._ETHNIC_GROUP != value))
				{
					this.OnETHNIC_GROUPChanging(value);
					this.SendPropertyChanging();
					this._ETHNIC_GROUP = value;
					this.SendPropertyChanged("ETHNIC_GROUP");
					this.OnETHNIC_GROUPChanged();
				}
			}
		}
		
		[Column(Storage="_TEL_NO", DbType="NVarChar(255)")]
		public string TEL_NO
		{
			get
			{
				return this._TEL_NO;
			}
			set
			{
				if ((this._TEL_NO != value))
				{
					this.OnTEL_NOChanging(value);
					this.SendPropertyChanging();
					this._TEL_NO = value;
					this.SendPropertyChanged("TEL_NO");
					this.OnTEL_NOChanged();
				}
			}
		}
		
		[Column(Storage="_FAX_NO", DbType="NVarChar(255)")]
		public string FAX_NO
		{
			get
			{
				return this._FAX_NO;
			}
			set
			{
				if ((this._FAX_NO != value))
				{
					this.OnFAX_NOChanging(value);
					this.SendPropertyChanging();
					this._FAX_NO = value;
					this.SendPropertyChanged("FAX_NO");
					this.OnFAX_NOChanged();
				}
			}
		}
		
		[Column(Storage="_ZIPCODE", DbType="NVarChar(255)")]
		public string ZIPCODE
		{
			get
			{
				return this._ZIPCODE;
			}
			set
			{
				if ((this._ZIPCODE != value))
				{
					this.OnZIPCODEChanging(value);
					this.SendPropertyChanging();
					this._ZIPCODE = value;
					this.SendPropertyChanged("ZIPCODE");
					this.OnZIPCODEChanged();
				}
			}
		}
		
		[Column(Storage="_ADDRESS", DbType="NVarChar(255)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[Column(Storage="_EMAIL", DbType="NVarChar(255)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[Column(Storage="_BLOOD_TYPE", DbType="NVarChar(255)")]
		public string BLOOD_TYPE
		{
			get
			{
				return this._BLOOD_TYPE;
			}
			set
			{
				if ((this._BLOOD_TYPE != value))
				{
					this.OnBLOOD_TYPEChanging(value);
					this.SendPropertyChanging();
					this._BLOOD_TYPE = value;
					this.SendPropertyChanged("BLOOD_TYPE");
					this.OnBLOOD_TYPEChanged();
				}
			}
		}
		
		[Column(Storage="_PREGNANCY_STATUS", DbType="NVarChar(255)")]
		public string PREGNANCY_STATUS
		{
			get
			{
				return this._PREGNANCY_STATUS;
			}
			set
			{
				if ((this._PREGNANCY_STATUS != value))
				{
					this.OnPREGNANCY_STATUSChanging(value);
					this.SendPropertyChanging();
					this._PREGNANCY_STATUS = value;
					this.SendPropertyChanged("PREGNANCY_STATUS");
					this.OnPREGNANCY_STATUSChanged();
				}
			}
		}
		
		[Column(Storage="_CURRENT_LOCATION", DbType="NVarChar(255)")]
		public string CURRENT_LOCATION
		{
			get
			{
				return this._CURRENT_LOCATION;
			}
			set
			{
				if ((this._CURRENT_LOCATION != value))
				{
					this.OnCURRENT_LOCATIONChanging(value);
					this.SendPropertyChanging();
					this._CURRENT_LOCATION = value;
					this.SendPropertyChanged("CURRENT_LOCATION");
					this.OnCURRENT_LOCATIONChanged();
				}
			}
		}
		
		[Column(Storage="_CURRENT_RESIDENCY", DbType="NVarChar(255)")]
		public string CURRENT_RESIDENCY
		{
			get
			{
				return this._CURRENT_RESIDENCY;
			}
			set
			{
				if ((this._CURRENT_RESIDENCY != value))
				{
					this.OnCURRENT_RESIDENCYChanging(value);
					this.SendPropertyChanging();
					this._CURRENT_RESIDENCY = value;
					this.SendPropertyChanged("CURRENT_RESIDENCY");
					this.OnCURRENT_RESIDENCYChanged();
				}
			}
		}
		
		[Column(Storage="_CURRENT_DEPARTMENT", DbType="NVarChar(255)")]
		public string CURRENT_DEPARTMENT
		{
			get
			{
				return this._CURRENT_DEPARTMENT;
			}
			set
			{
				if ((this._CURRENT_DEPARTMENT != value))
				{
					this.OnCURRENT_DEPARTMENTChanging(value);
					this.SendPropertyChanging();
					this._CURRENT_DEPARTMENT = value;
					this.SendPropertyChanged("CURRENT_DEPARTMENT");
					this.OnCURRENT_DEPARTMENTChanged();
				}
			}
		}
		
		[Column(Storage="_CURRENT_DOCTOR_ID", DbType="NVarChar(255)")]
		public string CURRENT_DOCTOR_ID
		{
			get
			{
				return this._CURRENT_DOCTOR_ID;
			}
			set
			{
				if ((this._CURRENT_DOCTOR_ID != value))
				{
					this.OnCURRENT_DOCTOR_IDChanging(value);
					this.SendPropertyChanging();
					this._CURRENT_DOCTOR_ID = value;
					this.SendPropertyChanged("CURRENT_DOCTOR_ID");
					this.OnCURRENT_DOCTOR_IDChanged();
				}
			}
		}
		
		[Column(Storage="_CURRENT_DOCTOR_NAME", DbType="NVarChar(255)")]
		public string CURRENT_DOCTOR_NAME
		{
			get
			{
				return this._CURRENT_DOCTOR_NAME;
			}
			set
			{
				if ((this._CURRENT_DOCTOR_NAME != value))
				{
					this.OnCURRENT_DOCTOR_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CURRENT_DOCTOR_NAME = value;
					this.SendPropertyChanged("CURRENT_DOCTOR_NAME");
					this.OnCURRENT_DOCTOR_NAMEChanged();
				}
			}
		}
		
		[Column(Storage="_ADMIT_DTTM", DbType="NVarChar(255)")]
		public string ADMIT_DTTM
		{
			get
			{
				return this._ADMIT_DTTM;
			}
			set
			{
				if ((this._ADMIT_DTTM != value))
				{
					this.OnADMIT_DTTMChanging(value);
					this.SendPropertyChanging();
					this._ADMIT_DTTM = value;
					this.SendPropertyChanged("ADMIT_DTTM");
					this.OnADMIT_DTTMChanged();
				}
			}
		}
		
		[Column(Storage="_DISCHARGE_DTTM", DbType="NVarChar(255)")]
		public string DISCHARGE_DTTM
		{
			get
			{
				return this._DISCHARGE_DTTM;
			}
			set
			{
				if ((this._DISCHARGE_DTTM != value))
				{
					this.OnDISCHARGE_DTTMChanging(value);
					this.SendPropertyChanging();
					this._DISCHARGE_DTTM = value;
					this.SendPropertyChanged("DISCHARGE_DTTM");
					this.OnDISCHARGE_DTTMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
